#version 430 core

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;



// Image buffers

layout(rgba32f, binding = 0) uniform image2D albedoTexture;

layout(rgba32f, binding = 1) uniform image2D luminanceTexture;

layout(r32f, binding = 2) uniform image2D depthTexture;

layout(r32i, binding = 3) uniform iimage2D normalTexture;

// SSBOs

struct material
{
    vec3 color;
    // 4 bytes padding
    vec3 emission;
    // 4 bytes padding
};

layout(std430, binding = 0) buffer brickListSSBO
{
    uint voxelMap[];
};

layout(std430, binding = 1) buffer bitmaskSSBO
{
    uint voxelBitmask[];
};

layout(std430, binding = 2) buffer palette
{
    material materialPalette[];
};

layout(std430, binding = 3) buffer inputData
{
    mat4 inverseCameraMatrix;
    vec3 cameraPosition;
    float randSalt;
    vec3 ambientLighting;
    ivec3 mapSize;
    ivec3 compoundMapSize;
    ivec3 compoundVoxelBitmaskSize;
};

struct teststruct
{
    int a;
    float b;
};

layout(std430, binding = 4) buffer testlist
{
    teststruct list[];
};

// Global vars

const float TWO_PI = 6.283185;

int samples = 2;
float invSamples = 1.0 / samples;
float jitterArc = TWO_PI / samples;
vec2 fragPosition;

float randSaltLocal;
vec3 ambientLightingLocal;
ivec3 mapSizeLocal;
ivec3 compoundMapSizeLocal;
ivec3 compoundVoxelBitmaskSizeLocal;

const int intMaxValue = 2147483647;
const float depthBias = -0.02;


// Function prototypes
void executePathTracing(vec3 origin, vec3 dir, out vec3 albedo, out vec3 luminance, out float depth, out int normal);

int trace        (vec3 origin, vec3 dir, out vec3 hitPos, out material hitMat, out int normal, out float depth);
int traceLast    (vec3 origin, vec3 dir, out material hitMat);
int traverse     (vec3 origin, vec3 dir, out vec3 hitPos, out material hitMat, out int normal, out float depth);  // Experimantal
int traverseLast (vec3 origin, vec3 dir, out material hitMat);

float minVec3(vec3 vect);
float maxVec3(vec3 vect);
float cart2Sph_Phi(vec3 vect);
float cart2Sph_Theta(vec3 vect);
float skyFactor(vec3 dir);
vec3 scatter(vec3 normal, int sampleIndex);
vec3 randomVector(vec3 key, int sampleIndex);
float random (vec2 point);
vec3 rotateVerticalByNormal(vec3 vector, int normal);

void main() 
{
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);

    fragPosition = vec2(texelCoord) / imageSize(albedoTexture) * 2 - 1;

    vec4 screenSpaceNear = vec4(fragPosition, 0, 1);
    vec4 screenSpaceFar = vec4(fragPosition, 1, 1);

    mat4 matrix = inverseCameraMatrix;

    vec4 near = screenSpaceNear * matrix;
    vec4 far = screenSpaceFar * matrix;

    vec3 rayDirection = normalize(far.xyz / far.w - near.xyz / near.w);

    randSaltLocal = randSalt;
    ambientLightingLocal = ambientLighting;
    mapSizeLocal = mapSize;
    compoundMapSizeLocal = compoundMapSize;
    compoundVoxelBitmaskSizeLocal = compoundVoxelBitmaskSize;
    vec3 albedo, lum; float depth; int normal;

    executePathTracing(cameraPosition, rayDirection, albedo, lum, depth, normal);
//    albedo = list[2].b > 0.8 ? vec3(1, 0, 0) : albedo; 
    imageStore(albedoTexture, texelCoord, vec4(albedo, 0));
    imageStore(luminanceTexture, texelCoord, vec4(lum, 0));
    imageStore(depthTexture, texelCoord, vec4(depth, 0, 0, 0));
    imageStore(normalTexture, texelCoord, ivec4(normal, 0, 0, 0));
}

int traceLast(vec3 origin, vec3 dir, out material hitMat)
{
    
    //initialization

    ivec3 voxelPosition = ivec3(origin);
    vec3 nextIntersectionTime;
    vec3 timeToCross = abs(1.0 / dir);
    ivec3 gridStep;
    uint voxelValue;
    float timeToClosestVoxel = float(
        voxelMap[voxelPosition.y * compoundMapSizeLocal.x * compoundMapSizeLocal.z + voxelPosition.z * compoundMapSizeLocal.x + (voxelPosition.x >> 2)] 
        >> ((voxelPosition.x & 3) * 8) & 255);
    int steps;
    uint voxelBit = 0;

    vec3 timeToEscape;

    if (dir.x < 0)
    {
        gridStep.x = -1;
        nextIntersectionTime.x = timeToCross.x * (origin.x - voxelPosition.x);
        timeToEscape.x = nextIntersectionTime.x + voxelPosition.x * timeToCross.x;
    }
    else if (dir.x > 0)
    {
        gridStep.x = 1;
        nextIntersectionTime.x = timeToCross.x * (voxelPosition.x + 1 - origin.x);
        timeToEscape.x = nextIntersectionTime.x + (mapSize.x - voxelPosition.x) * timeToCross.x;
    }
    else
    {
        gridStep.x = 0;
        timeToEscape.x = 3.402823466e+38;
    }

    if (dir.y < 0)
    {
        gridStep.y = -1;
        nextIntersectionTime.y = timeToCross.y * (origin.y - voxelPosition.y);
        timeToEscape.y = nextIntersectionTime.y + voxelPosition.y * timeToCross.y;
    }
    else if (dir.y > 0)
    {
        gridStep.y = 1;
        nextIntersectionTime.y = timeToCross.y * (voxelPosition.y + 1 - origin.y);
        timeToEscape.y = nextIntersectionTime.y + (mapSize.y - voxelPosition.y) * timeToCross.y;
    }
    else
    {
        gridStep.y = 0;
        timeToEscape.y = 3.402823466e+38;
    }

    if (dir.z < 0)
    {
        gridStep.z = -1;
        nextIntersectionTime.z = timeToCross.z * (origin.z - voxelPosition.z);
        timeToEscape.z = nextIntersectionTime.z + voxelPosition.z * timeToCross.z;
    }
    else if (dir.z > 0)
    {
        gridStep.z = 1;
        nextIntersectionTime.z = timeToCross.z * (voxelPosition.z + 1 - origin.z);
        timeToEscape.z = nextIntersectionTime.z + (mapSize.z - voxelPosition.z) * timeToCross.z;
    }
    else
    {
        gridStep.z = 0;
        timeToEscape.z = 3.402823466e+38;
    }

    float maxDepth = minVec3(timeToEscape) + depthBias;
    float depth;

    //traversal

    bool escaped = true;
    vec3 stepMask;
    do
	{
        steps = abs(int(dir.x * timeToClosestVoxel)) + abs(int(dir.y * timeToClosestVoxel)) + abs(int(dir.z * timeToClosestVoxel)) - 1;
        steps = steps < 1 ? 1 : steps;

        for (int i = 0; i < steps; i++)
        {
            stepMask = vec3(lessThanEqual(nextIntersectionTime.xyz, min(nextIntersectionTime.yzx, nextIntersectionTime.zxy)));

            vec3 a = (stepMask * nextIntersectionTime);
            depth = maxVec3(a);

            nextIntersectionTime += stepMask * timeToCross;
            voxelPosition += ivec3(stepMask) * gridStep;
        }

        if (depth > maxDepth) break;
		
        ivec3 maskRegion = ivec3(voxelPosition.x >> 2, voxelPosition.y >> 1, voxelPosition.z >> 2);
        ivec3 maskIndex = ivec3(voxelPosition.x & 3, voxelPosition.y & 1, voxelPosition.z & 3);
		
        voxelValue = voxelMap[voxelPosition.y * compoundMapSizeLocal.x * compoundMapSizeLocal.z + 
                                voxelPosition.z * compoundMapSizeLocal.x + 
                                maskRegion.x];
        voxelValue = (voxelValue >> (maskIndex.x * 8)) & 255;

        uint mask = voxelBitmask[maskRegion.y * compoundVoxelBitmaskSizeLocal.x * compoundVoxelBitmaskSizeLocal.z + 
                                    maskRegion.z * compoundVoxelBitmaskSizeLocal.x +
                                    maskRegion.x];
        voxelBit = mask & (1 << ((maskIndex.y << 4) + (maskIndex.z << 2) + maskIndex.x));
        if (voxelBit == 0)
        {
            timeToClosestVoxel = voxelValue;
        }
        else 
        { 
        escaped = false;
            break; 
        }

	} while (true);
    
    if (escaped) return 1;

    hitMat = materialPalette[voxelValue];
    return 0;
}

int trace(vec3 origin, vec3 dir, out vec3 hitPos, out material hitMat, out int normal, out float depth)
{
    // Initialization

    ivec3 voxelPosition = ivec3(origin);
    vec3 nextIntersectionTime;
    vec3 timeToCross = abs(1.0 / dir);
    ivec3 gridStep;
    uint voxelValue;
    int side = 0;
    float timeToClosestVoxel = float(
        voxelMap[voxelPosition.y * compoundMapSizeLocal.x * compoundMapSizeLocal.z + voxelPosition.z * compoundMapSizeLocal.x + (voxelPosition.x >> 2)] 
        >> ((voxelPosition.x & 3) * 8) & 255);
    uint voxelBit = 0;
    int steps;

    int InfoInteger = 0;

    vec3 timeToEscape;

    if (dir.x < 0)
    {
        gridStep.x = -1;
        nextIntersectionTime.x = timeToCross.x * (origin.x - voxelPosition.x);
        timeToEscape.x = nextIntersectionTime.x + voxelPosition.x * timeToCross.x;
    }
    else if (dir.x > 0)
    {
        gridStep.x = 1;
        nextIntersectionTime.x = timeToCross.x * (voxelPosition.x + 1 - origin.x);
        timeToEscape.x = nextIntersectionTime.x + (mapSizeLocal.x - voxelPosition.x - 1) * timeToCross.x;
    }
    else
    {
        gridStep.x = 0;
        timeToEscape.x = 3.402823466e+38;
    }

    if (dir.y < 0)
    {
        gridStep.y = -1;
        nextIntersectionTime.y = timeToCross.y * (origin.y - voxelPosition.y);
        timeToEscape.y = nextIntersectionTime.y + voxelPosition.y * timeToCross.y;
    }
    else if (dir.y > 0)
    {
        gridStep.y = 1;
        nextIntersectionTime.y = timeToCross.y * (voxelPosition.y + 1 - origin.y);
        timeToEscape.y = nextIntersectionTime.y + (mapSizeLocal.y - voxelPosition.y - 1) * timeToCross.y;
    }
    else
    {
        gridStep.y = 0;
        timeToEscape.y = 3.402823466e+38;
    }

    if (dir.z < 0)
    {
        gridStep.z = -1;
        nextIntersectionTime.z = timeToCross.z * (origin.z - voxelPosition.z);
        timeToEscape.z = nextIntersectionTime.z + voxelPosition.z * timeToCross.z;
    }
    else if (dir.z > 0)
    {
        gridStep.z = 1;
        nextIntersectionTime.z = timeToCross.z * (voxelPosition.z + 1 - origin.z);
        timeToEscape.z = nextIntersectionTime.z + (mapSizeLocal.z - voxelPosition.z - 1) * timeToCross.z;
    }
    else
    {
        gridStep.z = 0;
        timeToEscape.z = 3.402823466e+38;
    }

    float maxDepth = minVec3(timeToEscape) + depthBias;

    int maxIterations = 20;

    // Traversal

    bool escaped = true;
    vec3 stepMask;
    do
	{
        steps = abs(int(dir.x * timeToClosestVoxel)) + abs(int(dir.y * timeToClosestVoxel)) + abs(int(dir.z * timeToClosestVoxel)) - 1;
        steps = steps < 1 ? 1 : steps;
        steps = 1;

        for (int i = 0; i < steps; i++)
        {
            // IMPLEMENTATION WITH BRANCHING


//            if (nextIntersectionTime.x < nextIntersectionTime.y)
//		    {
//			    if (nextIntersectionTime.x < nextIntersectionTime.z)
//			    {
//				    voxelPosition.x += gridStep.x;
//                    depth = nextIntersectionTime.x;
//                    side = 0;
//				    nextIntersectionTime.x += timeToCross.x;
//			    }
//			    else
//			    {
//				    voxelPosition.z += gridStep.z;
//                    depth = nextIntersectionTime.z;
//                    side = 1;
//				    nextIntersectionTime.z += timeToCross.z;
//			    }
//		    }
//		    else
//		    {
//			    if (nextIntersectionTime.y < nextIntersectionTime.z)
//			    {
//				    voxelPosition.y += gridStep.y;
//                    depth = nextIntersectionTime.y;
//                    side = 2;
//				    nextIntersectionTime.y += timeToCross.y;
//			    }
//			    else
//			    {
//				    voxelPosition.z += gridStep.z;
//                    depth = nextIntersectionTime.z;
//                    side = 1;
//				    nextIntersectionTime.z += timeToCross.z;
//			    }
//		    }

            // BRANCHLESS

            stepMask = vec3(lessThanEqual(nextIntersectionTime.xyz, min(nextIntersectionTime.yzx, nextIntersectionTime.zxy)));

            vec3 a = (stepMask * nextIntersectionTime);
            depth = maxVec3(a);

            nextIntersectionTime += stepMask * timeToCross;
            voxelPosition += ivec3(stepMask) * gridStep;
        }

        if (depth > maxDepth) break;
		
        ivec3 maskPosition = ivec3(voxelPosition.x >> 2, voxelPosition.y >> 1, voxelPosition.z >> 2);
        ivec3 maskInternalIndex = ivec3(voxelPosition.x & 3, voxelPosition.y & 1, voxelPosition.z & 3);
		
        voxelValue = voxelMap[voxelPosition.y * compoundMapSizeLocal.x * compoundMapSizeLocal.z + 
                              voxelPosition.z * compoundMapSizeLocal.x + 
                              maskPosition.x];
        voxelValue = (voxelValue >> (maskInternalIndex.x * 8)) & 255;

        uint mask = voxelBitmask[maskPosition.y * compoundVoxelBitmaskSizeLocal.x * compoundVoxelBitmaskSizeLocal.z + 
                                 maskPosition.z * compoundVoxelBitmaskSizeLocal.x +
                                 maskPosition.x];
        voxelBit = mask & (1 << ((maskInternalIndex.y << 4) + (maskInternalIndex.z << 2) + maskInternalIndex.x));

        if (voxelBit == 0)
        {
            timeToClosestVoxel = voxelValue;
        }
        else 
        {
            escaped = false;
            break;
        }
        
	} while (true);

    if (escaped) return 1;

    depth += depthBias;
    hitPos = origin + dir * depth;
    hitMat = materialPalette[voxelValue];
    if (stepMask.y > 0)
    {
        if (gridStep.y == -1)
        {
            side = 0;
        }
        else 
        {
            side = 1;
        }
    }
    else if (stepMask.x > 0)
    {
        if (gridStep.x == 1)
        {
            side = 2;
        }
        else 
        {
            side = 3;
        }
    }
    else if (stepMask.z > 0)
    {
        if (gridStep.z == 1)
        {
            side = 4;
        }
        else 
        {
            side = 5;
        }
    }
    normal = side;
    return 0;
}

vec3 scatter(int normal, int sampleIndex)
{
    vec2 randomSampler = fragPosition.xy * sampleIndex * 68.8;
    float key1 = random(randomSampler); 
    float key2 = random((randomSampler * key1 * 22.314));
    float key3 = random(vec2(key1 * -12.3, key2 + 34));
    return rotateVerticalByNormal(randomVector(vec3(key1, key2, key3), sampleIndex), normal);
}

vec3 rotateVerticalByNormal(vec3 vector, int normal)
{
    switch (normal)
    {
        case 0: return vector;
        case 1: return vec3(vector.x, -vector.y, vector.z);
        case 2: return vec3(-vector.y, vector.x, vector.z);
        case 3: return vec3(vector.y, -vector.x, vector.z);
        case 4: return vec3(vector.x, vector.z, -vector.y);
        case 5: return vec3(vector.x, -vector.z, vector.y);
    }
    return vector;
}

void executePathTracing(vec3 origin, vec3 dir, out vec3 albedo, out vec3 luminance, out float depth, out int normal)
{
    vec3 firstHitPos;
    material firstHitMat;

    material secondHitMat;
    int secondHitResult;

    int firstHitResult = trace(origin, dir, firstHitPos, firstHitMat, normal, depth);

    if (firstHitResult == 1)
    {
        albedo = vec3(1);

        float factor = skyFactor(dir);
        luminance = ambientLightingLocal * factor;
        return;
    }
    if (firstHitResult != 0)
    {
        albedo = vec3(1, 0, 0);
        luminance = vec3(1);
        return;
    }

    vec3 indirectContribution = vec3(0);

    int i = 1;
    while(i <= samples)
    {
        vec3 scatteredDir = scatter(normal, i);
        secondHitResult = traceLast(firstHitPos, scatteredDir, secondHitMat);
        if (secondHitResult == 0)
        {
            indirectContribution += secondHitMat.emission;
            i++;
            continue;
        }
        if (secondHitResult == 1)
        {
            float factor = skyFactor(scatteredDir);
            indirectContribution += ambientLightingLocal * factor;
            i++;
            continue;
        }
        i++;
    }

    int exposedToSun = traceLast(firstHitPos, vec3(0.27, 0.8, 0.53), secondHitMat);
    vec3 sunExposure = vec3(0.7, 0.6, 0.4) * exposedToSun * clamp(dot(rotateVerticalByNormal(vec3(0, 1, 0), normal), vec3(0.27, 0.8, 0.53)), 0, 1);;
    albedo = firstHitMat.color;
    luminance = firstHitMat.emission + indirectContribution * invSamples + sunExposure;
    return;
}

vec3 randomVector(vec3 key, int sampleIndex)
{
    float theta = jitterArc * key.x + jitterArc * sampleIndex + TWO_PI * key.z;
    float phi = (-1 * sqrt(1 - key.y * key.y) + 1) * 1.370796 + 0.2;
    float cosPhi = cos(phi);
    return vec3(sin(theta) * cosPhi, sin(phi), cosPhi * cos(theta));
}

float random (vec2 point) 
{
    point *= randSaltLocal;
    return fract(sin(dot(point.xy, vec2(12.9898,78.233))) * 43758.5453123);
}

float minVec3(vec3 vect)
{
    return min(min(vect.x, vect.y), vect.z);
}

float maxVec3(vec3 vect)
{
    return max(max(vect.x, vect.y), vect.z);
}

float cart2Sph_Phi(vec3 vect)
{
    return atan(sqrt(vect.x * vect.x + vect.y * vect.y), vect.z) * 2;
}

float cart2Sph_Theta(vec3 vect)
{
    return atan(vect.y, vect.x) * 2;
}

float skyFactor(vec3 dir)
{
    return tanh(dir.y * 30) * 0.45 + 0.55;
}

int traverse(vec3 origin, vec3 dir, out vec3 hitPos, out material hitMat, out int normal, out float depth)
{
    // Vars

	vec3 timeToCrossSigned = 1.0 / dir;
    vec3 invTimeToCross = abs(dir);
	vec3 timeToCross = abs(timeToCrossSigned);
	ivec3 axisSigns;
	ivec3 voxPos = ivec3(floor(origin));
    depth = 0;
    uint voxelValue;
    uint voxelBit;
    uint DF = (voxelMap[voxPos.y * compoundMapSizeLocal.x * compoundMapSizeLocal.z + voxPos.z * compoundMapSizeLocal.x + (voxPos.x >> 2)] 
               >> ((voxPos.x & 3) * 8) & 255);
    bool escaped = true;
    vec3 timeToEscape;

    // Initialization

    if (dir.x < 0)
    {
        timeToEscape.x = voxPos.x * timeToCross.x;
        axisSigns.x = -1;
    }
    else if (dir.x > 0)
    {
        timeToEscape.x = (mapSizeLocal.x - voxPos.x) * timeToCross.x;
        axisSigns.x = 1;
    }
    else
    {
        timeToEscape.x = intMaxValue;
        axisSigns.x = 0;
    }

    if (dir.y < 0)
    {
        timeToEscape.y = voxPos.y * timeToCross.y;
        axisSigns.y = -1;
    }
    else if (dir.y > 0)
    {
        timeToEscape.y = (mapSizeLocal.y - voxPos.y) * timeToCross.y;
        axisSigns.y = 1;
    }
    else
    {
        timeToEscape.y = intMaxValue;
        axisSigns.y = 0;
    }

    if (dir.z < 0)
    {
        timeToEscape.z = voxPos.z * timeToCross.z;
        axisSigns.z = -1;
    }
    else if (dir.z > 0)
    {
        timeToEscape.z = (mapSizeLocal.z - voxPos.z) * timeToCross.z;
        axisSigns.z = 1;
    }
    else
    {
        timeToEscape.z = intMaxValue;
        axisSigns.z = 0;
    }

    float maxDepth = minVec3(timeToEscape);

	vec3 nextIntersectionTime = (voxPos - origin + 0.5 + vec3(axisSigns) * 0.5) * timeToCrossSigned;
    while (true)
    {
        // Traversal
        
//        if (DF > 1)
//        {
//            if (DF > 2)
//            {
//                vec3 m = floor(invTimeToCross * float(DF - 1));
//                nextIntersectionTime += m * timeToCross;
//                ivec3 mi = ivec3(m);
//                voxPos += mi * axisSigns;
//            }
//            ivec3 mask = ivec3(step(nextIntersectionTime.xyz, nextIntersectionTime.yzx) * step(nextIntersectionTime.xyz, nextIntersectionTime.zxy));
//            nextIntersectionTime += mask * timeToCross;
//            voxPos += ivec3(mask) * axisSigns;
//        }
        
		ivec3 mask = ivec3(step(nextIntersectionTime.xyz, nextIntersectionTime.yzx) * step(nextIntersectionTime.xyz, nextIntersectionTime.zxy));
        voxPos += mask * axisSigns;

        if (minVec3(nextIntersectionTime) > maxDepth) break;

        // Voxel retrieval

        ivec3 maskRegion = ivec3(voxPos.x >> 2, voxPos.y >> 1, voxPos.z >> 2);
        ivec3 maskIndex = ivec3(voxPos.x & 3, voxPos.y & 1, voxPos.z & 3);
		
        voxelValue = voxelMap[voxPos.y * compoundMapSizeLocal.x * compoundMapSizeLocal.z + 
                                voxPos.z * compoundMapSizeLocal.x + 
                                maskRegion.x];
        voxelValue = (voxelValue >> (maskIndex.x * 8)) & 255;

        uint bitmaskBlock = voxelBitmask[maskRegion.y * compoundVoxelBitmaskSizeLocal.x * compoundVoxelBitmaskSizeLocal.z + 
                                    maskRegion.z * compoundVoxelBitmaskSizeLocal.x +
                                    maskRegion.x];
        voxelBit = bitmaskBlock & (1 << ((maskIndex.y << 4) + (maskIndex.z << 2) + maskIndex.x));

        if (voxelBit == 0)
        {
            DF = voxelValue;
        }
        else 
        {
            escaped = false;
            break;
        }

        // Only update nextIntersectionTime after conditional break to preserve voxel entering depth
		nextIntersectionTime += mask * timeToCross;
    }    
    if (escaped) 
    {
        return 1;
    }

    // Get depth and normal
    if (nextIntersectionTime.x < nextIntersectionTime.y)
    {
        if (nextIntersectionTime.x < nextIntersectionTime.z)
        {
            depth = nextIntersectionTime.x;
            normal = 0;
        }
        else 
        {
            depth = nextIntersectionTime.z;
            normal = 1;
        }
    }
    else 
    {
        if (nextIntersectionTime.y < nextIntersectionTime.z)
        {
            depth = nextIntersectionTime.y;
            normal = 2;
        }
        else 
        {
            depth = nextIntersectionTime.z;
            normal = 1;
        }
    }

    if (normal == 2)
    {
        if (axisSigns.y == -1)
        {
            normal = 0;
        }
        else 
        {
            normal = 1;
        }
    }
    else if (normal == 0)
    {
        if (axisSigns.x == 1)
        {
            normal = 2;
        }
        else 
        {
            normal = 3;
        }
    }
    else if (normal == 1)
    {
        if (axisSigns.z == 1)
        {
            normal = 4;
        }
        else 
        {
            normal = 5;
        }
    }

    hitPos = origin + dir * depth;
    hitMat = materialPalette[voxelValue];
    return 0;
}

int traverseLast(vec3 origin, vec3 dir, out material hitMat) 
{
    // Vars

	vec3 timeToCrossSigned = 1.0 / dir;
    vec3 invTimeToCross = abs(dir);
	vec3 timeToCross = abs(timeToCrossSigned);
	ivec3 axisSigns;
	ivec3 voxPos = ivec3(floor(origin));
    uint voxelValue;
    uint voxelBit;
    uint DF = (voxelMap[voxPos.y * compoundMapSizeLocal.x * compoundMapSizeLocal.z + voxPos.z * compoundMapSizeLocal.x + (voxPos.x >> 2)] 
               >> ((voxPos.x & 3) * 8) & 255);
    bool escaped = true;
    vec3 timeToEscape;

    // Initialization

	vec3 nextIntersectionTime = (voxPos - origin + 0.5 + vec3(axisSigns) * 0.5) * timeToCrossSigned;

    if (dir.x < 0)
    {
        timeToEscape.x = voxPos.x * timeToCross.x;
        axisSigns.x = -1;
    }
    else if (dir.x > 0)
    {
        timeToEscape.x = (mapSizeLocal.x - voxPos.x) * timeToCross.x;
        axisSigns.x = 1;
    }
    else
    {
        timeToEscape.x = intMaxValue;
    }

    if (dir.y < 0)
    {
        timeToEscape.y = voxPos.y * timeToCross.y;
        axisSigns.y = -1;
    }
    else if (dir.y > 0)
    {
        timeToEscape.y = (mapSizeLocal.y - voxPos.y) * timeToCross.y;
        axisSigns.y = 1;
    }
    else
    {
        timeToEscape.y = intMaxValue;
    }

    if (dir.z < 0)
    {
        timeToEscape.z = voxPos.z * timeToCross.z;
        axisSigns.z = -1;
    }
    else if (dir.z > 0)
    {
        timeToEscape.z = (mapSizeLocal.z - voxPos.z) * timeToCross.z;
        axisSigns.z = 1;
    }
    else
    {
        timeToEscape.z = intMaxValue;
    }

    float maxDepth = minVec3(timeToEscape);
    while (true)
    {
        // Traversal

//        if (DF > 1)
//        {
//            if (DF > 2)
//            {
//                vec3 m = floor(invTimeToCross * float(DF - 1));
//                nextIntersectionTime += m * timeToCross;
//                ivec3 mi = ivec3(m);
//                voxPos += mi * axisSigns;
//            }
//            ivec3 mask = ivec3(step(nextIntersectionTime.xyz, nextIntersectionTime.yzx) * step(nextIntersectionTime.xyz, nextIntersectionTime.zxy));
//            nextIntersectionTime += mask * timeToCross;
//            voxPos += ivec3(mask) * axisSigns;
//        }
        
		ivec3 mask = ivec3(step(nextIntersectionTime.xyz, nextIntersectionTime.yzx) * step(nextIntersectionTime.xyz, nextIntersectionTime.zxy));
        voxPos += mask * axisSigns;

        if (minVec3(nextIntersectionTime) > maxDepth) break;

        // Voxel retrieval

        ivec3 maskRegion = ivec3(voxPos.x >> 2, voxPos.y >> 1, voxPos.z >> 2);
        ivec3 maskIndex = ivec3(voxPos.x & 3, voxPos.y & 1, voxPos.z & 3);
		
        voxelValue = voxelMap[voxPos.y * compoundMapSizeLocal.x * compoundMapSizeLocal.z + 
                                voxPos.z * compoundMapSizeLocal.x + 
                                maskRegion.x];
        voxelValue = (voxelValue >> (maskIndex.x * 8)) & 255;

        uint bitmaskBlock = voxelBitmask[maskRegion.y * compoundVoxelBitmaskSizeLocal.x * compoundVoxelBitmaskSizeLocal.z + 
                                    maskRegion.z * compoundVoxelBitmaskSizeLocal.x +
                                    maskRegion.x];
        voxelBit = bitmaskBlock & (1 << ((maskIndex.y << 4) + (maskIndex.z << 2) + maskIndex.x));

        if (voxelBit == 0)
        {
            DF = voxelValue;
        }
        else 
        {
            escaped = false;
            break;
        }

        // Only update nextIntersectionTime after conditional break to preserve voxel entering depth
		nextIntersectionTime += mask * timeToCross;
    }    
    if (escaped) 
    {
        return 1;
    }
    hitMat = materialPalette[voxelValue];
    return 0;
}