#version 430 core

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;



// Image buffers

layout(rgba32f, binding = 0) uniform image2D albedoTexture;

layout(rgba32f, binding = 1) uniform image2D luminanceTexture;

layout(r32f, binding = 2) uniform image2D depthTexture;

layout(r32i, binding = 3) uniform iimage2D normalTexture;

// SSBOs

struct material
{
    vec3 color;
    // 4 bytes padding
    vec3 emission;
    // 4 bytes padding
};

struct voxelBrick
{
    uint bitmask1;
    uint bitmask2;
    uint[16] packs;
};

layout(std430, binding = 0) buffer brickListSSBO
{
    uint brickList[];
};

layout(std430, binding = 1) buffer brickIndicesSSBO
{
    int brickIndices[];
};

layout(std430, binding = 2) buffer palette
{
    material materialPalette[];
};

layout(std430, binding = 3) buffer inputData
{
    mat4 inverseCameraMatrix;
    vec3 cameraPosition;
    float randSalt;
    vec3 ambientLighting;
    float time;
    ivec3 mapSize;
    ivec3 voxelBrickmapSize;
};


// Global vars

const float TWO_PI = 6.283185;

int samples = 1;
float invSamples = 1.0 / samples;
float jitterArc = TWO_PI / samples;
vec2 fragPosition;

float randSaltLocal;
vec3 ambientLightingLocal;
ivec3 mapSizeLocal;
ivec3 voxelBrickmapSizeLocal;

const int intMaxValue = 2147483647;
const float depthBias = -0.02;
const int brickSizeInUINTS = 18;


// Function prototypes
void executePathTracing(vec3 origin, vec3 dir, out vec3 albedo, out vec3 luminance, out float depth, out int normal);

int trace        (vec3 origin, vec3 dir, out vec3 hitPos, out material hitMat, out int normal, out float depth);
int traceLast    (vec3 origin, vec3 dir, out material hitMat);
int traverse     (vec3 origin, vec3 dir, out vec3 hitPos, out material hitMat, out int normal, out float depth);  // Experimantal
int traverseLast (vec3 origin, vec3 dir, out material hitMat);

float minVec3(vec3 vect);
float maxVec3(vec3 vect);
float cart2Sph_Phi(vec3 vect);
float cart2Sph_Theta(vec3 vect);
float skyFactor(vec3 dir);
vec3 scatter(vec3 normal, int sampleIndex);
vec3 randomVector(vec3 key, int sampleIndex);
float random (vec2 point);
vec3 rotateVerticalByNormal(vec3 vector, int normal);
uint getBrickIndex(ivec3 voxelPosition); 
uint getVoxelValue(ivec3 voxelPosition);
uint getVoxelValueAndBit(ivec3 voxelPosition, out uint voxelBit);

bool indicate = false;
vec3 indicationColor;

void main() 
{
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);

    fragPosition = vec2(texelCoord) / imageSize(albedoTexture) * 2 - 1;

    vec4 screenSpaceNear = vec4(fragPosition, 0, 1);
    vec4 screenSpaceFar = vec4(fragPosition, 1, 1);

    mat4 matrix = inverseCameraMatrix;

    vec4 near = screenSpaceNear * matrix;
    vec4 far = screenSpaceFar * matrix;

    vec3 rayDirection = normalize(far.xyz / far.w - near.xyz / near.w);

    randSaltLocal = randSalt;
    ambientLightingLocal = ambientLighting;
    mapSizeLocal = mapSize;
    voxelBrickmapSizeLocal = voxelBrickmapSize;
    vec3 albedo, lum; float depth; int normal;

    executePathTracing(cameraPosition, rayDirection, albedo, lum, depth, normal);

    //if (getBrickIndex(ivec3(cameraPosition)) == -1) indicate = true;

    if (indicate) 
    { 
        albedo = indicationColor; 
        lum = vec3(1);
    }

    imageStore(albedoTexture, texelCoord, vec4(albedo, 0));
    imageStore(luminanceTexture, texelCoord, vec4(lum, 0));
    imageStore(depthTexture, texelCoord, vec4(depth, 0, 0, 0));
    imageStore(normalTexture, texelCoord, ivec4(normal, 0, 0, 0));
}

int traceLast(vec3 origin, vec3 dir, out material hitMat)
{
    
    //initialization

    ivec3 voxelPosition = ivec3(origin);
    vec3 nextIntersectionTime;
    vec3 timeToCross = abs(1.0 / dir);
    ivec3 gridStep;
    uint voxelValue;
    float timeToClosestVoxel = float(getVoxelValue(voxelPosition));
    int steps;
    uint voxelBit = 0;

    vec3 timeToEscape;

    if (dir.x < 0)
    {
        gridStep.x = -1;
        nextIntersectionTime.x = timeToCross.x * (origin.x - voxelPosition.x);
        timeToEscape.x = nextIntersectionTime.x + voxelPosition.x * timeToCross.x;
    }
    else if (dir.x > 0)
    {
        gridStep.x = 1;
        nextIntersectionTime.x = timeToCross.x * (voxelPosition.x + 1 - origin.x);
        timeToEscape.x = nextIntersectionTime.x + (mapSize.x - voxelPosition.x) * timeToCross.x;
    }
    else
    {
        gridStep.x = 0;
        timeToEscape.x = 3.402823466e+38;
    }

    if (dir.y < 0)
    {
        gridStep.y = -1;
        nextIntersectionTime.y = timeToCross.y * (origin.y - voxelPosition.y);
        timeToEscape.y = nextIntersectionTime.y + voxelPosition.y * timeToCross.y;
    }
    else if (dir.y > 0)
    {
        gridStep.y = 1;
        nextIntersectionTime.y = timeToCross.y * (voxelPosition.y + 1 - origin.y);
        timeToEscape.y = nextIntersectionTime.y + (mapSize.y - voxelPosition.y) * timeToCross.y;
    }
    else
    {
        gridStep.y = 0;
        timeToEscape.y = 3.402823466e+38;
    }

    if (dir.z < 0)
    {
        gridStep.z = -1;
        nextIntersectionTime.z = timeToCross.z * (origin.z - voxelPosition.z);
        timeToEscape.z = nextIntersectionTime.z + voxelPosition.z * timeToCross.z;
    }
    else if (dir.z > 0)
    {
        gridStep.z = 1;
        nextIntersectionTime.z = timeToCross.z * (voxelPosition.z + 1 - origin.z);
        timeToEscape.z = nextIntersectionTime.z + (mapSize.z - voxelPosition.z) * timeToCross.z;
    }
    else
    {
        gridStep.z = 0;
        timeToEscape.z = 3.402823466e+38;
    }

    float maxDepth = minVec3(timeToEscape) + depthBias;
    float depth;

    //traversal

    bool escaped = true;
    vec3 stepMask;
    do
	{
        stepMask = vec3(lessThanEqual(nextIntersectionTime.xyz, min(nextIntersectionTime.yzx, nextIntersectionTime.zxy)));

        vec3 a = (stepMask * nextIntersectionTime);
        depth = maxVec3(a);

        nextIntersectionTime += stepMask * timeToCross;
        voxelPosition += ivec3(stepMask) * gridStep;

        if (depth > maxDepth) break;
		
        voxelValue = getVoxelValueAndBit(voxelPosition, voxelBit);

        if (voxelBit == 0)
        {
            timeToClosestVoxel = voxelValue;
        }
        else 
        { 
        escaped = false;
            break; 
        }

	} while (true);
    
    if (escaped) return 1;

    hitMat = materialPalette[voxelValue];
    return 0;
}

int trace(vec3 origin, vec3 dir, out vec3 hitPos, out material hitMat, out int normal, out float depth)
{
    // Initialization

    ivec3 voxelPosition = ivec3(origin);
    vec3 nextIntersectionTime;
    vec3 timeToCross = abs(1.0 / dir);
    ivec3 gridStep;
    uint voxelValue;
    int side = 0;
    float timeToClosestVoxel = getVoxelValue(voxelPosition);
    uint voxelBit = 0;
    int steps;

    int InfoInteger = 0;

    vec3 timeToEscape;

    if (dir.x < 0)
    {
        gridStep.x = -1;
        nextIntersectionTime.x = timeToCross.x * (origin.x - voxelPosition.x);
        timeToEscape.x = nextIntersectionTime.x + voxelPosition.x * timeToCross.x;
    }
    else if (dir.x > 0)
    {
        gridStep.x = 1;
        nextIntersectionTime.x = timeToCross.x * (voxelPosition.x + 1 - origin.x);
        timeToEscape.x = nextIntersectionTime.x + (mapSizeLocal.x - voxelPosition.x - 1) * timeToCross.x;
    }
    else
    {
        gridStep.x = 0;
        timeToEscape.x = 3.402823466e+38;
    }

    if (dir.y < 0)
    {
        gridStep.y = -1;
        nextIntersectionTime.y = timeToCross.y * (origin.y - voxelPosition.y);
        timeToEscape.y = nextIntersectionTime.y + voxelPosition.y * timeToCross.y;
    }
    else if (dir.y > 0)
    {
        gridStep.y = 1;
        nextIntersectionTime.y = timeToCross.y * (voxelPosition.y + 1 - origin.y);
        timeToEscape.y = nextIntersectionTime.y + (mapSizeLocal.y - voxelPosition.y - 1) * timeToCross.y;
    }
    else
    {
        gridStep.y = 0;
        timeToEscape.y = 3.402823466e+38;
    }

    if (dir.z < 0)
    {
        gridStep.z = -1;
        nextIntersectionTime.z = timeToCross.z * (origin.z - voxelPosition.z);
        timeToEscape.z = nextIntersectionTime.z + voxelPosition.z * timeToCross.z;
    }
    else if (dir.z > 0)
    {
        gridStep.z = 1;
        nextIntersectionTime.z = timeToCross.z * (voxelPosition.z + 1 - origin.z);
        timeToEscape.z = nextIntersectionTime.z + (mapSizeLocal.z - voxelPosition.z - 1) * timeToCross.z;
    }
    else
    {
        gridStep.z = 0;
        timeToEscape.z = 3.402823466e+38;
    }

    float maxDepth = minVec3(timeToEscape) + depthBias;

    int i = 0;

    // Traversal

    bool escaped = true;
    vec3 stepMask;
    do
	{
        stepMask = vec3(lessThanEqual(nextIntersectionTime.xyz, min(nextIntersectionTime.yzx, nextIntersectionTime.zxy)));

        vec3 a = (stepMask * nextIntersectionTime);
        depth = maxVec3(a);

        nextIntersectionTime += stepMask * timeToCross;
        voxelPosition += ivec3(stepMask) * gridStep;

        i++;

        if (depth > maxDepth) break;
		
        voxelValue = getVoxelValueAndBit(voxelPosition, voxelBit);

        if (voxelBit == 0)
        {
            timeToClosestVoxel = voxelValue;
        }
        else 
        {
            escaped = false;
            break;
        }
        
	} while (i < 500);

    if (i == 500) return 2;
    if (escaped) return 1;

    depth += depthBias;
    hitPos = origin + dir * depth;
    hitMat = materialPalette[voxelValue];
    if (stepMask.y > 0)
    {
        if (gridStep.y == -1)
        {
            side = 0;
        }
        else 
        {
            side = 1;
        }
    }
    else if (stepMask.x > 0)
    {
        if (gridStep.x == 1)
        {
            side = 2;
        }
        else 
        {
            side = 3;
        }
    }
    else if (stepMask.z > 0)
    {
        if (gridStep.z == 1)
        {
            side = 4;
        }
        else 
        {
            side = 5;
        }
    }
    normal = side;
    return 0;
}

vec3 scatter(int normal, int sampleIndex)
{
    vec2 randomSampler = fragPosition.xy * sampleIndex * 68.8;
    float key1 = random(randomSampler); 
    float key2 = random((randomSampler * key1));
    float key3 = random(vec2(key1 * -12.3, key2 + 34));
    return rotateVerticalByNormal(randomVector(vec3(key1, key2, key3), sampleIndex), normal);
}

vec3 rotateVerticalByNormal(vec3 vector, int normal)
{
    switch (normal)
    {
        case 0: return vector;
        case 1: return vec3(vector.x, -vector.y, vector.z);
        case 2: return vec3(-vector.y, vector.x, vector.z);
        case 3: return vec3(vector.y, -vector.x, vector.z);
        case 4: return vec3(vector.x, vector.z, -vector.y);
        case 5: return vec3(vector.x, -vector.z, vector.y);
    }
    return vector;
}

vec3 vecNormal(int normal)
{
    switch (normal)
    {
        case 0: return vec3(0, 1, 0);
        case 1: return vec3(0, -1, 0);
        case 2: return vec3(-1, 0, 0);
        case 3: return vec3(1, 0, 0);
        case 4: return vec3(0, 0, -1);
        case 5: return vec3(0, 0, 1);
    }
    return vec3(0, 1, 0);
}

void executePathTracing(vec3 origin, vec3 dir, out vec3 albedo, out vec3 luminance, out float depth, out int normal)
{
    vec3 firstHitPos;
    material firstHitMat;

    material secondHitMat;
    int secondHitResult;

    int firstHitResult = trace(origin, dir, firstHitPos, firstHitMat, normal, depth);

    if (firstHitResult == 1)
    {
        albedo = vec3(1);

        float factor = skyFactor(dir);
        luminance = ambientLightingLocal * factor;
        return;
    }
    if (firstHitResult != 0)
    {
        albedo = vec3(1, 0, 0);
        luminance = vec3(1);
        return;
    }

    vec3 indirectContribution = vec3(0);

    int i = 1;
    while(i <= samples)
    {
        vec3 scatteredDir = scatter(normal, i);
        secondHitResult = traceLast(firstHitPos, scatteredDir, secondHitMat);
        if (secondHitResult == 0)
        {
            indirectContribution += secondHitMat.emission * dot(vecNormal(normal), scatteredDir);
            i++;
            continue;
        }
        if (secondHitResult == 1)
        {
            float factor = skyFactor(scatteredDir);
            indirectContribution += ambientLightingLocal * factor * dot(vecNormal(normal), scatteredDir);
            i++;
            continue;
        }
        i++;
    }

    vec3 fl_hpos; int fl_n; float fl_d;
    float sunPhi = mod(time*0.3, TWO_PI);
    float sunTheta = mod(time*0.5, TWO_PI);
    float cosPhi = cos(sunPhi);
    vec3 sunDirection = vec3(sin(sunTheta) * cosPhi, sin(sunPhi), cos(sunTheta) * cosPhi);

    int exposedToSun = trace(firstHitPos, sunDirection, fl_hpos, secondHitMat, fl_n, fl_d);
    vec3 sunContribution = vec3(0.8, 0.8, 0.7) * exposedToSun * dot(vecNormal(normal), sunDirection) * clamp(dot(rotateVerticalByNormal(vec3(0, 1, 0), normal), vec3(0.27, 0.8, 0.53)), 0, 1);;

    albedo = firstHitMat.color;
    luminance = firstHitMat.emission + indirectContribution * invSamples + sunContribution;
    return;
}

uint getVoxelValueAndBit(ivec3 voxelPosition, out uint voxelBit) 
{
    ivec3 brickIndexPosition = ivec3(voxelPosition.x >> 2, voxelPosition.y >> 2, voxelPosition.z >> 2);
    int brickIndex = brickIndices[brickIndexPosition.y * voxelBrickmapSizeLocal.z * voxelBrickmapSizeLocal.x + 
                                  brickIndexPosition.z * voxelBrickmapSizeLocal.x +
                                  brickIndexPosition.x];
    if (brickIndex == -1) 
    {
        voxelBit = 0;
        return 0;
    }

    ivec3 voxelLocalPosition = (voxelPosition & 3);
    int brickRootLocation = brickIndex * brickSizeInUINTS;

    uint voxelPack = brickList[brickRootLocation + 2 + ((voxelLocalPosition.y << 2) + voxelLocalPosition.z)];
    if (voxelLocalPosition.y < 2)
    {
        uint bitmask = brickList[brickRootLocation];
        uint mask = 1 << ((voxelLocalPosition.y << 4) + (voxelLocalPosition.z << 2) + voxelLocalPosition.x);
        voxelBit = bitmask & mask;
    }
    else
    {
        uint bitmask = brickList[brickRootLocation + 1];
        voxelLocalPosition.y -= 2;
        uint mask = 1 << ((voxelLocalPosition.y << 4) + (voxelLocalPosition.z << 2) + voxelLocalPosition.x);
        voxelBit = bitmask & mask;
    }
    int shift = voxelLocalPosition.x << 3;
    
    uint voxelValue = (voxelPack & (255 << shift)) >> shift;
    
    return voxelValue;

}

uint getVoxelValue(ivec3 voxelPosition) 
{
    uint brickIndex = getBrickIndex(voxelPosition);
    if (brickIndex == -1) return 0;
    ivec3 voxelLocalPosition = (voxelPosition & 3);
    uint voxelPack = brickList[brickIndex * brickSizeInUINTS + 2 + ((voxelLocalPosition.y << 2) + voxelLocalPosition.z)];
    int shift = voxelLocalPosition.x << 3;
    return (voxelPack & (255 << shift)) >> shift;
}

uint getBrickIndex(ivec3 voxelPosition) 
{
    ivec3 brickIndexPosition = ivec3(voxelPosition.x >> 2, voxelPosition.y >> 2, voxelPosition.z >> 2);
    return brickIndices[brickIndexPosition.y * voxelBrickmapSizeLocal.x * voxelBrickmapSizeLocal.z + 
                        brickIndexPosition.z * voxelBrickmapSizeLocal.x +
                        brickIndexPosition.x];
}

vec3 randomVector(vec3 key, int sampleIndex)
{
    float theta = jitterArc * key.x + jitterArc * sampleIndex + TWO_PI * key.z;
    float phi = (-1 * sqrt(1 - key.y * key.y) + 1) * 1.370796 + 0.2;
    float cosPhi = cos(phi);
    return vec3(sin(theta) * cosPhi, sin(phi), cos(theta) * cosPhi);
}

float random (vec2 point) 
{
    point *= randSaltLocal;
    return fract(sin(dot(point.xy, vec2(12.9898,78.233))) * 43758.5453123);
}

float minVec3(vec3 vect)
{
    return min(min(vect.x, vect.y), vect.z);
}

float maxVec3(vec3 vect)
{
    return max(max(vect.x, vect.y), vect.z);
}

float cart2Sph_Phi(vec3 vect)
{
    return atan(sqrt(vect.x * vect.x + vect.y * vect.y), vect.z) * 2;
}

float cart2Sph_Theta(vec3 vect)
{
    return atan(vect.y, vect.x) * 2;
}

float skyFactor(vec3 dir)
{
    return tanh(dir.y * 30) * 0.45 + 0.55;
}

