<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	<PublishAot>false</PublishAot>
	<GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1591;8500</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1591;8500</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\ava6.png" />
    <None Remove="Resources\Graphics\Shaders\Test.comp" />
    <None Remove="Resources\Graphics\Shaders\TestFrag.frag" />
    <None Remove="Resources\Graphics\Shaders\voxelRender.frag" />
    <None Remove="Resources\Graphics\Shaders\voxelRender.vert" />
    <None Remove="Resources\Graphics\Shaders\voxelRenderFlat.frag" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ImGui.NET" Version="1.91.0.1" />
    <PackageReference Include="OpenTK" Version="4.8.2" />
    <PackageReference Include="StbImageSharp" Version="2.30.15" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Libs\DisposeExt\DisposeExt.csproj" />
    <ProjectReference Include="..\Libs\GLAV\GLAV.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Resources\Graphics\Shaders\copy_tex8_shader.comp">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Graphics\Shaders\ImGui\imgui_fragment_shader.frag">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Graphics\Shaders\ImGui\imgui_vertex_shader.vert">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Graphics\Shaders\taa_shader.comp">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Graphics\Shaders\voxel_compositing_shader.frag">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Graphics\Shaders\voxel_compositing_shader.vert">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Graphics\Shaders\voxel_path_tracing_shader.comp">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Content\Graphics\Textures\map.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Content\Graphics\Textures\map_hdr.hdr">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ProjectExtensions><VisualStudio><UserProperties /></VisualStudio></ProjectExtensions>

</Project>
