#version 430 core
layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(rgba32f, binding = 0) uniform image2D lumNewImg;
layout(rgba32f, binding = 1) uniform image2D lumAccumImg;

uniform float intensity;

void main() 
{
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID);
    vec2 uv = vec2(texelCoord) / imageSize(lumNewImg); 

    vec4 lumNew = imageLoad(lumNewImg, texelCoord);
    vec4 lumOld = imageLoad(lumAccumImg, texelCoord);
    vec4 color = mix(lumNew, lumOld, intensity);

    imageStore(lumNewImg, texelCoord, color);
    imageStore(lumAccumImg, texelCoord, color);
}