#version 430 core
layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(rgba32f, binding = 0) uniform image2D lumOutImg;
uniform sampler2D lumNewImg;
uniform sampler2D lumOldImg;
uniform sampler2D depth_motionTex;

uniform float intensity;

void main() 
{
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID) - ivec2(1);
    vec2 uv = vec2(texelCoord) / imageSize(lumOutImg); 

    vec2 displacementUV = texture2D(depth_motionTex, uv).gb;
    vec2 targetUV = uv + displacementUV;
    if (targetUV.x > 1 || targetUV.x < 0 || targetUV.y > 1 || targetUV.y < 0) 
    {
        imageStore(lumOutImg, texelCoord, texture2D(lumNewImg, uv));
        return;
    }

    vec4 lum0 = texture2D(lumNewImg, uv);
    vec4 lum1 = texture2D(lumOldImg, targetUV);
    vec4 color = mix(lum0, lum1, intensity);

    imageStore(lumOutImg, texelCoord, mix(vec4(abs(displacementUV), 0, 1), color, 0.9));
}