#version 430 core

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;


// Texture samplers

uniform sampler2D skyTex;


// Image buffers

layout(rgba32f, binding = 0) uniform image2D luminanceTexture;

layout(rgba32f, binding = 1) uniform image2D depth_motionTexture;

layout(r32i, binding = 2) uniform iimage2D normalTexture;


// Input

struct material
{
    vec3 color;
    // 4 bytes padding
    vec3 emission;
    // 4 bytes padding
};

struct voxelBrick
{
    uint bitmask1;
    uint bitmask2;
    uint[16] packs;
};

layout(std430, binding = 0) buffer brickListSSBO
{
    uint brickList[];
};

layout(std430, binding = 1) buffer brickIndicesSSBO
{
    int brickIndices[];
};

layout(std430, binding = 2) buffer palette
{
    material materialPalette[];
};

layout(std140, binding = 3) buffer inputData
{
    mat4 cameraMatrix;
    mat4 invCameraMatrix;
    mat4 prevInvCameraMatrix;
    vec3 cameraPosition;
    float randSalt;
};

uniform ivec3 mapSize;
uniform ivec3 voxelBrickmapSize;
uniform vec3 sunDirection = vec3(0.31, 0.82, 0.47);
uniform vec3 sunColor = vec3(2.8, 2.65, 2);
uniform float sunDirectionJitter = 0.01;

uniform int samples = 1;


// Global vars

const float PI = 3.141592;
const float TWO_PI = 6.283185;
const float INV_PI = 1 / PI;
const float INV_TWO_PI = 1 / TWO_PI;

const int intMaxValue = 2147483647;

float invSamples = 1.0 / samples;
float jitterArc = TWO_PI / samples;
vec2 fragPosition;

float randSaltLocal;

const float depthBias = -0.002;
const int brickSizeInUINTS = 18;


// Function prototypes

void executePathTracing(vec3 origin, vec3 dir, out vec3 luminance, out float depth, out int normal);

int trace        (vec3 origin, vec3 dir, out vec3 hitPos, out material hitMat, out int normal, out float depth);
int traceLast    (vec3 origin, vec3 dir, out material hitMat);

float minVec3(vec3 vect);
float maxVec3(vec3 vect);
float cart2Sph_Phi(vec3 vect);
float cart2Sph_Theta(vec3 vect);
vec3 rodriguesRotation(vec3 v, vec3 axis, float theta);
vec3 simpleRodriguesRotation(vec3 v, vec3 normal, float theta);
vec3 rotateVerticalByNormal(vec3 vector, int normal);

vec3 skySample(vec3 dir);
vec3 sunSample(vec3 pos, vec3 dir);

vec3 scatter(vec3 normal, int sampleIndex);
vec3 randomVector(vec3 key, int sampleIndex);
float random (vec2 point);
vec3 jitterVector(vec3 v, float theta, float amount);

uint getBrickIndex(ivec3 voxelPosition); 
uint getVoxelValue(ivec3 voxelPosition);
uint getVoxelValueAndBit(ivec3 voxelPosition, out uint voxelBit);

bool indicate = false;
vec3 indicationColor;

void main() 
{
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
    vec2 uv = vec2(texelCoord) / imageSize(luminanceTexture);
    fragPosition = uv * 2 - 1;

    randSaltLocal = randSalt;

    vec4 farFrag = vec4(fragPosition, 1, 1);
    vec4 far = invCameraMatrix * farFrag;
    vec3 rayDirection = normalize(far.xyz / far.w);

    vec3 lum; float depth; int normal;
    executePathTracing(cameraPosition, rayDirection, lum, depth, normal);

    vec4 prevFar = prevInvCameraMatrix * farFrag;
    vec4 prevFarFragOnCurrent = cameraMatrix * (normalize(prevFar) * depth);
    vec2 motion = 0.5 * (farFrag.xy - prevFarFragOnCurrent.xy); // 0.5 converts from [-1; 1] to [0; 1] (uv)

    imageStore(luminanceTexture, texelCoord, vec4(lum, 0));
    imageStore(depth_motionTexture, texelCoord, vec4(depth, motion, 0));
    imageStore(normalTexture, texelCoord, ivec4(normal, 0, 0, 0));
}

int traceLast(vec3 origin, vec3 dir, out material hitMat)
{
    
    //initialization

    ivec3 voxelPosition = ivec3(origin);
    vec3 nextIntersectionTime;
    vec3 timeToCross = abs(1.0 / dir);
    ivec3 gridStep;
    uint voxelValue;
    float timeToClosestVoxel = float(getVoxelValue(voxelPosition));
    int steps;
    uint voxelBit = 0;

    vec3 timeToEscape;

    if (dir.x < 0)
    {
        gridStep.x = -1;
        nextIntersectionTime.x = timeToCross.x * (origin.x - voxelPosition.x);
        timeToEscape.x = nextIntersectionTime.x + voxelPosition.x * timeToCross.x;
    }
    else if (dir.x > 0)
    {
        gridStep.x = 1;
        nextIntersectionTime.x = timeToCross.x * (voxelPosition.x + 1 - origin.x);
        timeToEscape.x = nextIntersectionTime.x + (mapSize.x - voxelPosition.x) * timeToCross.x;
    }
    else
    {
        gridStep.x = 0;
        timeToEscape.x = 3.402823466e+38;
    }

    if (dir.y < 0)
    {
        gridStep.y = -1;
        nextIntersectionTime.y = timeToCross.y * (origin.y - voxelPosition.y);
        timeToEscape.y = nextIntersectionTime.y + voxelPosition.y * timeToCross.y;
    }
    else if (dir.y > 0)
    {
        gridStep.y = 1;
        nextIntersectionTime.y = timeToCross.y * (voxelPosition.y + 1 - origin.y);
        timeToEscape.y = nextIntersectionTime.y + (mapSize.y - voxelPosition.y) * timeToCross.y;
    }
    else
    {
        gridStep.y = 0;
        timeToEscape.y = 3.402823466e+38;
    }

    if (dir.z < 0)
    {
        gridStep.z = -1;
        nextIntersectionTime.z = timeToCross.z * (origin.z - voxelPosition.z);
        timeToEscape.z = nextIntersectionTime.z + voxelPosition.z * timeToCross.z;
    }
    else if (dir.z > 0)
    {
        gridStep.z = 1;
        nextIntersectionTime.z = timeToCross.z * (voxelPosition.z + 1 - origin.z);
        timeToEscape.z = nextIntersectionTime.z + (mapSize.z - voxelPosition.z) * timeToCross.z;
    }
    else
    {
        gridStep.z = 0;
        timeToEscape.z = 3.402823466e+38;
    }

    float maxDepth = minVec3(timeToEscape) + depthBias;
    float depth;

    //traversal

    bool escaped = true;
    vec3 stepMask;
    do
	{
        stepMask = vec3(lessThanEqual(nextIntersectionTime.xyz, min(nextIntersectionTime.yzx, nextIntersectionTime.zxy)));

        vec3 a = (stepMask * nextIntersectionTime);
        depth = maxVec3(a);

        nextIntersectionTime += stepMask * timeToCross;
        voxelPosition += ivec3(stepMask) * gridStep;

        if (depth > maxDepth) break;
		
        voxelValue = getVoxelValueAndBit(voxelPosition, voxelBit);

        if (voxelBit == 0)
        {
            timeToClosestVoxel = voxelValue;
        }
        else 
        { 
            escaped = false;
            break; 
        }

	} while (true);
    
    if (escaped) return 1;

    hitMat = materialPalette[voxelValue];
    return 0;
}

int trace(vec3 origin, vec3 dir, out vec3 hitPos, out material hitMat, out int normal, out float depth)
{
    // Initialization

    ivec3 voxelPosition = ivec3(origin);
    vec3 nextIntersectionTime;
    vec3 timeToCross = abs(1.0 / dir);
    ivec3 gridStep;
    uint voxelValue;
    int side = 0;
    float timeToClosestVoxel = getVoxelValue(voxelPosition);
    uint voxelBit = 0;
    int steps;

    int InfoInteger = 0;

    vec3 timeToEscape;

    if (dir.x < 0)
    {
        gridStep.x = -1;
        nextIntersectionTime.x = timeToCross.x * (origin.x - voxelPosition.x);
        timeToEscape.x = nextIntersectionTime.x + voxelPosition.x * timeToCross.x;
    }
    else if (dir.x > 0)
    {
        gridStep.x = 1;
        nextIntersectionTime.x = timeToCross.x * (voxelPosition.x + 1 - origin.x);
        timeToEscape.x = nextIntersectionTime.x + (mapSize.x - voxelPosition.x - 1) * timeToCross.x;
    }
    else
    {
        gridStep.x = 0;
        timeToEscape.x = 3.402823466e+38;
    }

    if (dir.y < 0)
    {
        gridStep.y = -1;
        nextIntersectionTime.y = timeToCross.y * (origin.y - voxelPosition.y);
        timeToEscape.y = nextIntersectionTime.y + voxelPosition.y * timeToCross.y;
    }
    else if (dir.y > 0)
    {
        gridStep.y = 1;
        nextIntersectionTime.y = timeToCross.y * (voxelPosition.y + 1 - origin.y);
        timeToEscape.y = nextIntersectionTime.y + (mapSize.y - voxelPosition.y - 1) * timeToCross.y;
    }
    else
    {
        gridStep.y = 0;
        timeToEscape.y = 3.402823466e+38;
    }

    if (dir.z < 0)
    {
        gridStep.z = -1;
        nextIntersectionTime.z = timeToCross.z * (origin.z - voxelPosition.z);
        timeToEscape.z = nextIntersectionTime.z + voxelPosition.z * timeToCross.z;
    }
    else if (dir.z > 0)
    {
        gridStep.z = 1;
        nextIntersectionTime.z = timeToCross.z * (voxelPosition.z + 1 - origin.z);
        timeToEscape.z = nextIntersectionTime.z + (mapSize.z - voxelPosition.z - 1) * timeToCross.z;
    }
    else
    {
        gridStep.z = 0;
        timeToEscape.z = 3.402823466e+38;
    }

    float maxDepth = minVec3(timeToEscape) + depthBias;

    int i = 0;

    // Traversal

    bool escaped = true;
    vec3 stepMask;
    do
	{
        stepMask = vec3(lessThanEqual(nextIntersectionTime.xyz, min(nextIntersectionTime.yzx, nextIntersectionTime.zxy)));

        vec3 a = (stepMask * nextIntersectionTime);
        depth = maxVec3(a) - depthBias;

        nextIntersectionTime += stepMask * timeToCross;
        voxelPosition += ivec3(stepMask) * gridStep;

        i++;

        if (depth > maxDepth) break;
		
        voxelValue = getVoxelValueAndBit(voxelPosition, voxelBit);

        if (voxelBit == 0)
        {
            timeToClosestVoxel = voxelValue;
        }
        else 
        {
            escaped = false;
            break;
        }
        
	} while (true);

    if (escaped) return 1;

    depth += depthBias;
    hitPos = origin + dir * depth;
    hitMat = materialPalette[voxelValue];
    if (stepMask.y > 0)
    {
        if (gridStep.y == -1)
        {
            side = 0;
        }
        else 
        {
            side = 1;
        }
    }
    else if (stepMask.x > 0)
    {
        if (gridStep.x == 1)
        {
            side = 2;
        }
        else 
        {
            side = 3;
        }
    }
    else if (stepMask.z > 0)
    {
        if (gridStep.z == 1)
        {
            side = 4;
        }
        else 
        {
            side = 5;
        }
    }
    normal = side;
    return 0;
}

vec3 scatter(int normal, int sampleIndex)
{
    vec2 randomSampler = fragPosition.xy * sampleIndex * 68.8;
    float key1 = random(randomSampler); 
    float key2 = random((randomSampler * key1));
    float key3 = random(vec2(key1 * -12.3, key2 + 34));
    return rotateVerticalByNormal(randomVector(vec3(key1, key2, key3), sampleIndex), normal);
}

vec3 rotateVerticalByNormal(vec3 vector, int normal)
{
    switch (normal)
    {
        case 0: return vector;
        case 1: return vec3(vector.x, -vector.y, vector.z);
        case 2: return vec3(-vector.y, vector.x, vector.z);
        case 3: return vec3(vector.y, -vector.x, vector.z);
        case 4: return vec3(vector.x, vector.z, -vector.y);
        case 5: return vec3(vector.x, -vector.z, vector.y);
    }
    return vector;
}

vec3 vecNormal(int normal)
{
    switch (normal)
    {
        case 0: return vec3(0, 1, 0);
        case 1: return vec3(0, -1, 0);
        case 2: return vec3(-1, 0, 0);
        case 3: return vec3(1, 0, 0);
        case 4: return vec3(0, 0, -1);
        case 5: return vec3(0, 0, 1);
    }
    return vec3(0, 1, 0);
}

void executePathTracing(vec3 origin, vec3 dir, out vec3 luminance, out float depth, out int normal)
{
    vec3 firstHitPos;
    material firstHitMat;

    material secondHitMat;
    int secondHitResult;

    int firstHitResult = trace(origin, dir, firstHitPos, firstHitMat, normal, depth);

    if (firstHitResult == 1)
    {
        depth = 1;
        luminance = skySample(dir);
        return;
    }
    if (firstHitResult == 2)
    {
        luminance = vec3(1, 0, 0);
        return;
    }

    vec3 indirectContribution = vec3(0);

    vec3 fl_hpos; int fl_n; float fl_d;
    int exposedToSun;

    int i = 1;
    while(i <= samples)
    {
        vec3 secondHitPos;
        int secondNormal;
        float secondDepth;

        vec3 scatteredDir = scatter(normal, i);
        secondHitResult = trace(firstHitPos, scatteredDir, secondHitPos, secondHitMat, secondNormal, secondDepth);
        
        if (secondHitResult == 0)
        {
            float incomingCosineWeight = dot(vecNormal(normal), scatteredDir);
            indirectContribution += secondHitMat.emission * incomingCosineWeight;

            float key1 = random(fragPosition.xy * 78.12 * i) * TWO_PI;
            float key2 = random(vec2(key1 * 32.2, key1 * 51.1)) * sunDirectionJitter;
            indirectContribution += sunSample(secondHitPos, jitterVector(sunDirection, key1, key2)) * secondHitMat.color * clamp(dot(vecNormal(secondNormal), sunDirection), 0, 1) * incomingCosineWeight;
            i++;
            continue;
        }
        if (secondHitResult == 1)
        {
            indirectContribution += skySample(scatteredDir) * dot(vecNormal(normal), scatteredDir);
            i++;
            continue;
        }
        i++;
    }

    float key1 = random(fragPosition.xy * 92.92) * TWO_PI;
    float key2 = random(vec2(key1 * 32.2, key1 * 51.1)) * sunDirectionJitter;
    indirectContribution += sunSample(firstHitPos, jitterVector(sunDirection, key1, key2)) * clamp(dot(vecNormal(normal), sunDirection), 0, 1);

    luminance = firstHitMat.emission + indirectContribution * invSamples * firstHitMat.color;
    return;
}

uint getVoxelValueAndBit(ivec3 voxelPosition, out uint voxelBit) 
{
    ivec3 brickIndexPosition = ivec3(voxelPosition.x >> 2, voxelPosition.y >> 2, voxelPosition.z >> 2);
    int brickIndex = brickIndices[brickIndexPosition.y * voxelBrickmapSize.z * voxelBrickmapSize.x + 
                                  brickIndexPosition.z * voxelBrickmapSize.x +
                                  brickIndexPosition.x];
    if (brickIndex == -1) 
    {
        voxelBit = 0;
        return 0;
    }

    ivec3 voxelLocalPosition = (voxelPosition & 3);
    int brickRootLocation = brickIndex * brickSizeInUINTS;

    uint voxelPack = brickList[brickRootLocation + 2 + ((voxelLocalPosition.y << 2) + voxelLocalPosition.z)];
    if (voxelLocalPosition.y < 2)
    {
        uint bitmask = brickList[brickRootLocation];
        uint mask = 1 << ((voxelLocalPosition.y << 4) + (voxelLocalPosition.z << 2) + voxelLocalPosition.x);
        voxelBit = bitmask & mask;
    }
    else
    {
        uint bitmask = brickList[brickRootLocation + 1];
        voxelLocalPosition.y -= 2;
        uint mask = 1 << ((voxelLocalPosition.y << 4) + (voxelLocalPosition.z << 2) + voxelLocalPosition.x);
        voxelBit = bitmask & mask;
    }
    int shift = voxelLocalPosition.x << 3;
    
    uint voxelValue = (voxelPack & (255 << shift)) >> shift;
    
    return voxelValue;

}

uint getVoxelValue(ivec3 voxelPosition) 
{
    uint brickIndex = getBrickIndex(voxelPosition);
    if (brickIndex == -1) return 0;
    ivec3 voxelLocalPosition = (voxelPosition & 3);
    uint voxelPack = brickList[brickIndex * brickSizeInUINTS + 2 + ((voxelLocalPosition.y << 2) + voxelLocalPosition.z)];
    int shift = voxelLocalPosition.x << 3;
    return (voxelPack & (255 << shift)) >> shift;
}

uint getBrickIndex(ivec3 voxelPosition) 
{
    ivec3 brickIndexPosition = ivec3(voxelPosition.x >> 2, voxelPosition.y >> 2, voxelPosition.z >> 2);
    return brickIndices[brickIndexPosition.y * voxelBrickmapSize.x * voxelBrickmapSize.z + 
                        brickIndexPosition.z * voxelBrickmapSize.x +
                        brickIndexPosition.x];
}

vec3 randomVector(vec3 key, int sampleIndex)
{
    float theta = jitterArc * key.x + jitterArc * sampleIndex + TWO_PI * key.z;
    float phi = (-1 * sqrt(1 - key.y * key.y) + 1) * 1.370796 + 0.2;
    float cosPhi = cos(phi);
    return vec3(sin(theta) * cosPhi, sin(phi), cos(theta) * cosPhi);
}

float random (vec2 point) 
{
    point *= randSaltLocal;
    return fract(sin(dot(point.xy, vec2(12.9898,78.233))) * 43758.5453123);
}

float minVec3(vec3 vect)
{
    return min(min(vect.x, vect.y), vect.z);
}

float maxVec3(vec3 vect)
{
    return max(max(vect.x, vect.y), vect.z);
}

float cart2Sph_Phi(vec3 vect)
{
    return atan(sqrt(vect.x * vect.x + vect.y * vect.y), vect.z) * 2;
}

float cart2Sph_Theta(vec3 vect)
{
    return atan(vect.y, vect.x) * 2;
}

vec3 skySample(vec3 dir)
{
//    float theta = atan(dir.z, dir.x);
//    float phi = asin(dir.y);
//
//    vec2 uv = vec2(theta * INV_TWO_PI + 0.5, phi * INV_PI + 0.5);
//
//    return texture2D(skyTex, uv).rgb;
    return vec3(0.75, 1.3, 1.9);
}

vec3 sunSample(vec3 pos, vec3 dir)
{
    vec3 fl_hpos; int fl_n; float fl_d; material fl_mat;
    return sunColor * trace(pos, dir, fl_hpos, fl_mat, fl_n, fl_d);
}

vec3 rodriguesRotation(vec3 v, vec3 axis, float theta)
{
    float cosTheta = cos(theta);
    return v * cosTheta + cross(axis, v) * sin(theta) + axis * dot(axis, v) * (1 - cosTheta);
}
vec3 simpleRodriguesRotation(vec3 v, vec3 normal, float theta)
{
    return cos(theta) * v + sin(theta) * cross(v, normal);
}

vec3 jitterVector(vec3 v, float theta, float amount)
{
    return rodriguesRotation(simpleRodriguesRotation(v, cross(v, vec3(1, 0, 0)), amount), v, theta);
}