<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <PackageId />
    <Title>GLAV</Title>
    <Authors>Tile37</Authors>
    <Description>A thin object-oriented abstraction over the OpenTK's OpenGL API.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK" Version="4.8.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DisposeExt\DisposeExt.csproj" />
  </ItemGroup>

</Project>
