<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	<PublishAot>false</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Content\ava6.png" />
    <None Remove="Content\Graphics\Shaders\tempAntiAliasingShader.frag" />
    <None Remove="Content\Graphics\Shaders\tempAntiAliasingShader.vert" />
    <None Remove="Content\Graphics\Shaders\Test.comp" />
    <None Remove="Content\Graphics\Shaders\TestFrag.frag" />
    <None Remove="Content\Graphics\Shaders\Testing\TestVert.vert" />
    <None Remove="Content\Graphics\Shaders\voxelCompositing.frag" />
    <None Remove="Content\Graphics\Shaders\voxelCompositing.vert" />
    <None Remove="Content\Graphics\Shaders\voxelPostprocessingShader.frag" />
    <None Remove="Content\Graphics\Shaders\voxelPostprocessingShader.vert" />
    <None Remove="Content\Graphics\Shaders\voxelRender.frag" />
    <None Remove="Content\Graphics\Shaders\voxelRender.vert" />
    <None Remove="Content\Graphics\Shaders\voxelRenderFlat.frag" />
    <None Remove="Content\Graphics\Shaders\VoxelRender\voxelRenderComputeBrickmap.comp" />
    <None Remove="Content\Graphics\Textures\router.png" />
    <None Remove="Content\Graphics\UI\ImGuiStyles\style.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Content\Graphics\UI\ImGuiStyles\style.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Content\Graphics\Shaders\Testing\TestFrag.frag">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Graphics\Shaders\Testing\Test.comp" />
    <EmbeddedResource Include="Content\Graphics\Shaders\Testing\TestVert.vert">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Graphics\Shaders\VoxelRender\voxelRenderComputeBrickmap.comp" />
    <EmbeddedResource Include="Content\Graphics\Textures\router.png" />
    <EmbeddedResource Include="Content\Graphics\Shaders\VoxelRender\voxelRenderCompute.comp" />
    <EmbeddedResource Include="Content\Graphics\Shaders\tempAntiAliasingShader.vert">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Graphics\Shaders\voxelCompositing.frag">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Graphics\Shaders\tempAntiAliasingShader.frag">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Graphics\Shaders\voxelPostprocessingShader.frag">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Graphics\Shaders\voxelPostprocessingShader.vert">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Graphics\Shaders\voxelCompositing.vert">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Graphics\Shaders\VoxelRender\voxelRenderFlat.frag">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Graphics\Shaders\VoxelRender\voxelRender.frag">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Graphics\Shaders\VoxelRender\voxelRender.vert">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DisposeExt" Version="1.0.0" />
    <PackageReference Include="GLAV" Version="1.0.0" />
    <PackageReference Include="ImGui.NET" Version="1.91.0.1" />
    <PackageReference Include="OpenTK" Version="4.8.2" />
    <PackageReference Include="StbImageSharp" Version="2.27.14" />
  </ItemGroup>

  <ProjectExtensions><VisualStudio><UserProperties /></VisualStudio></ProjectExtensions>

</Project>
