#version 430 core

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;


// Texture samplers

layout(location = 7) uniform sampler2D skyTex;


// Image variables

layout(rgba32f, binding = 0) uniform image2D directIllum_depthImg;
layout(rgba32f, binding = 3) uniform image2D indirectIllumImg;

layout(rgba32f, binding = 1) uniform image2D normalCompound_motionImg;

// Input

struct material
{
    vec3 color;
    float colorVariance;
    vec3 emission;
    // 4 bytes padding
};

layout(std430, binding = 0) buffer brickValueListSSBO
{
    uint brickValueList[];
};
layout(std430, binding = 1) buffer brickOccupancyListSSBO
{
    uint brickOccupancyList[];
};

layout(std430, binding = 2) buffer brickIndicesSSBO
{
    int brickIndices[];
};

layout(std430, binding = 3) buffer palette
{
    material materialPalette[];
};

layout(std140, binding = 4) buffer inputData
{
    mat4 cameraMatrix;
    mat4 invCameraMatrix;
    mat4 prevCameraMatrix;
    mat4 invPrevCameraMatrix;
    vec3 cameraPosition;
    float randSalt;
    vec3 prevCameraPosition;
};

layout(location = 0) uniform ivec3 mapSize;
layout(location = 1) uniform ivec3 voxelBrickmapSize;
layout(location = 2) uniform vec3 sunDirection;
layout(location = 3) uniform vec3 sunColor = vec3(6.8, 4.65, 2) * 4;
layout(location = 4) uniform float sunDirectionJitter = 0.01;
layout(location = 8) uniform float fov = 80.0; 

layout(location = 5) uniform int cycle = 0;
layout(location = 6) uniform int samples = 1;
float invSamples = 1.0 / samples;


// Global vars

const float PI = 3.141592;
const float TWO_PI = 6.283185;
const float INV_PI = 1.0 / PI;
const float INV_TWO_PI = 1.0 / TWO_PI;

const uint MAX_UINT = 4294967295u;
const float INV_MAX_UINT = 1.0 / MAX_UINT;


vec2 uv;
vec2 fragPosition;
float jitterArc = TWO_PI / samples;
float arcDisplacement;

float randSaltLocal;

const float depthBias = -0.001;
const int brickSizeInUINTS = 16;


// Function prototypes

void executePathTracing(vec3 origin, vec3 dir, out vec3 directIllum, out vec3 indirectIllum, out float depth, out int normal, out vec3 hitPosition);

int raycast(vec3 origin, vec3 dir, out vec3 hitPosition, out ivec3 voxelHitPosition, out float depth, out int normal);
bool traverseBrick(uint bitmask0, uint bitmask1, vec3 startingPosition, ivec3 voxelPosition, vec3 dir, vec3 timeToCross, out ivec3 hitVoxel, inout int lastAxis, out float intersectionTime);

float minVec3(vec3 vect);
float maxVec3(vec3 vect);
int indexOfMinVec3(vec3 vect);
int indexOfMaxVec3(vec3 vect);
vec3 sph2Cart(float phi, float theta);

vec3 rodriguesRotation(vec3 v, vec3 axis, float theta);
vec3 simpleRodriguesRotation(vec3 v, vec3 normal, float theta);
vec3 rotateVerticalByNormal(vec3 vector, int normal);
int normalIndexFromDir(vec3 dir, int axis);

vec3 skySample(vec3 dir);
vec3 sunSample(vec3 pos, vec3 dir);

vec3 getDiffuseReflectionDir(int normal, int sampleIndex);
vec3 randomVector(vec2 key, int sampleIndex);
float rand01From_vec2(vec2 point);
uint wangHashFrom_uvec3(uvec3 point);
vec3 jitterVector(vec3 v, float theta, float amount);
vec3 vecNormal(int normal);

int getBrickValueDirect(ivec3 brickPosition);
uint getVoxelValue(ivec3 voxelPosition);
uint getVoxelBit(uint bitmask0, uint bitmask1, uint voxelIndex);

bool showDebug = false;
vec4 debugColor = vec4(1, 1, 0, 0);

void main() 
{
    ivec2 keeper = textureSize(skyTex, 0);

    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 resolution = imageSize(directIllum_depthImg);
    uv = (vec2(texelCoord) + 0.5) / resolution;
    fragPosition = uv * 2 - 1;

    randSaltLocal = randSalt;
    arcDisplacement = rand01From_vec2(uv * (randSalt - 1));
    invSamples = 1.0 / samples;

    vec4 viewPoint = vec4(fragPosition, 1, 1);
    vec4 transformedViewPoint = invCameraMatrix * viewPoint;
    vec3 rayDirection = normalize(transformedViewPoint.xyz / transformedViewPoint.w);

    vec3 directIllum, indirectIllum; float depth = 0; int normal; vec3 hitPos;
    executePathTracing(cameraPosition, rayDirection, directIllum, indirectIllum, depth, normal, hitPos);

    vec2 prevUV;
    vec2 motion;
    vec3 prevCameraToHitPos = hitPos - prevCameraPosition;

    vec4 normalCompound_Motion = imageLoad(normalCompound_motionImg, texelCoord);

    if (normal != -1)
    {
        // Find reprojection coord
        vec3 prevRayDirection = normalize(prevCameraToHitPos);
        vec4 prevViewPoint = prevCameraMatrix * vec4(prevRayDirection, 0);
        prevUV = fma(prevViewPoint.xy / prevViewPoint.w, vec2(0.5), vec2(0.5));

        if (any(lessThanEqual(prevUV, vec2(0))) || any(greaterThanEqual(prevUV, vec2(1))))
        {
            motion = vec2(-12, -12);
        }
        else
        {
            ivec2 reprojectionCoord = ivec2(prevUV * resolution);

            vec4 prevNormalCompound_motion = imageLoad(normalCompound_motionImg, reprojectionCoord);
            float prevDepth = prevNormalCompound_motion.y;

            int prevReprojectedNormal = (int(prevNormalCompound_motion.x) >> 3 * cycle) & 7;

            if (normal == prevReprojectedNormal)
            {
                vec2 prevFrag = (reprojectionCoord / vec2(resolution)) * 2 - 1;
                vec4 prevNDC = vec4(prevFrag + vec2(0.5) / resolution, 1, 1);
                vec4 prevNearestRayDirIntermediate = invPrevCameraMatrix * prevNDC;
                vec3 prevNearestRayDir = normalize(prevNearestRayDirIntermediate.xyz / prevNearestRayDirIntermediate.w);

                vec3 prevHit = prevNearestRayDir * prevDepth + prevCameraPosition;

                if (abs(prevHit[normal >> 1] - hitPos[normal >> 1]) > clamp(0.01 * (prevDepth) * 0.5, 0.2, 0.999f))
                {
                    motion = vec2(16);
                }
                else
                {
                    prevHit[normal >> 1] = hitPos[normal >> 1];
                    float radPedPixel = fov / resolution.y;
                    float rayDiffTriangleBase = sin(radPedPixel) * prevDepth * 2;
                    if (abs(distance(prevHit, hitPos)) < (dot(vecNormal(normal), prevRayDirection) + 1.3) * rayDiffTriangleBase)
                    {
                        motion = prevUV - uv;
                    }
                    else
                    {
                        motion = vec2(14);
                    }
                }
            }
            else 
            {
                motion = vec2(3);
            }
        }
    }
    else 
    {
        normal = 0;
        depth = 1e38;
        motion = vec2(15);
    }
    

    int prevNormalAtCurrentPixel = (int(normalCompound_Motion.x) >> 3 * cycle) & 7;
    int normalCompound = (prevNormalAtCurrentPixel << (cycle * 3)) | (normal << (cycle * -3 + 3)) | (normal << 6) | (prevNormalAtCurrentPixel << 9);
    imageStore(normalCompound_motionImg, texelCoord, vec4(normalCompound, normalCompound_Motion.y, motion));
    imageStore(directIllum_depthImg, texelCoord, showDebug ? debugColor : vec4(directIllum, depth));
    imageStore(indirectIllumImg, texelCoord, vec4(indirectIllum, depth));
}


void executePathTracing(vec3 origin, vec3 dir, out vec3 directIllum, out vec3 indirectIllum, out float depth, out int normal, out vec3 hitPosition)
{
    ivec3 firstHitVoxel;
    material firstHitMat;
    material secondHitMat;
    vec3 firstHitNormal;

    int firstHitResult = raycast(origin, dir, hitPosition, firstHitVoxel, depth, normal);
    hitPosition += dir * depthBias;
    firstHitMat = materialPalette[getVoxelValue(firstHitVoxel)];
    firstHitNormal = vecNormal(normal);

    firstHitMat.color = clamp(firstHitMat.color + wangHashFrom_uvec3(firstHitVoxel) * INV_MAX_UINT * firstHitMat.colorVariance - firstHitMat.colorVariance * 0.5, vec3(0), vec3(INV_PI));

    int secondHitResult;

    if (firstHitResult == 1)
    {
        directIllum = skySample(dir);
        normal = -1;
        return;
    }
    if (firstHitResult == 2)
    {
        directIllum = vec3(1, 0.8, 0.2);
        return;
    }

    vec3 indirectContribution = vec3(0);

    int i = 1;
    while(i <= samples)
    {
        vec3 secondHitPos;
        ivec3 secondHitVoxel;
        int secondHitNormalInt;
        float secondHitDepth;

        vec3 scatteredDir;
        scatteredDir = getDiffuseReflectionDir(normal, i);
        
        secondHitResult = raycast(hitPosition, scatteredDir, secondHitPos, secondHitVoxel, secondHitDepth, secondHitNormalInt);
        secondHitPos += scatteredDir * depthBias;
        secondHitMat = materialPalette[getVoxelValue(secondHitVoxel)];

        float cosWeight0 = clamp(dot(firstHitNormal, scatteredDir), 0, 1);

        if (secondHitResult == 0)
        {
            indirectContribution += secondHitMat.emission * cosWeight0;
            indirectContribution += sunSample(secondHitPos, sunDirection) * secondHitMat.color * clamp(dot(vecNormal(secondHitNormalInt), sunDirection), 0, 1) * cosWeight0;
        }
        else if (secondHitResult == 1)
        {
            indirectContribution += skySample(scatteredDir) * cosWeight0;
        }
        i++;
    }

    vec3 directLighting = sunSample(hitPosition, sunDirection) * clamp(dot(firstHitNormal, sunDirection), 0, 1);

    directIllum = directLighting * firstHitMat.color + firstHitMat.emission;
    indirectIllum = indirectContribution * invSamples * firstHitMat.color;
}

const float MIN_SAFE_DF = 1.8;

int raycast(vec3 origin, vec3 dir, out vec3 hitPosition, out ivec3 voxelHitPosition, out float depth, out int normal)
{
    vec3 dir_safe_div;
    const float epsilon = 1e-7f;

    dir_safe_div.x = (abs(dir.x) < epsilon) ? ( (dir.x >= 0.0f) ? epsilon : -epsilon ) : dir.x;
    dir_safe_div.y = (abs(dir.y) < epsilon) ? ( (dir.y >= 0.0f) ? epsilon : -epsilon ) : dir.y;
    dir_safe_div.z = (abs(dir.z) < epsilon) ? ( (dir.z >= 0.0f) ? epsilon : -epsilon ) : dir.z;


    //dir = normalize(dir);
    ivec3 originVoxel = ivec3(origin);
    ivec3 brickPosition = originVoxel >> 2;
    vec3 rayPosition = origin / 4; // rayPosition is in brick space
    int brickValue = getBrickValueDirect(brickPosition);
    ivec3 brickOffset = originVoxel & (~3);
    vec3 timeToCross = 1.0f / abs(dir_safe_div);
    ivec3 gridStep = ivec3(sign(dir));
    ivec3 hitVoxel;
    float intersectionTime;
    vec3 entrance;
    int lastAxis;
    depth = 0;

    dir_safe_div = 1 / dir_safe_div;

    // Traversing origin brick
    if (brickValue >= 0)
    {
        uint bitmask0 = brickOccupancyList[(brickValue << 1)];
        uint bitmask1 = brickOccupancyList[(brickValue << 1) + 1];

        entrance = origin - brickOffset;

        bool hit = traverseBrick(bitmask0, bitmask1, entrance, originVoxel & 3, dir, timeToCross, hitVoxel, lastAxis, intersectionTime);
            
        depth = intersectionTime * 0.25;
        if (hit)
        {   
            depth = intersectionTime;
            hitPosition = dir * intersectionTime + origin;
            voxelHitPosition = hitVoxel + brickOffset;
            normal = normalIndexFromDir(dir, lastAxis);
            return 0;
        }   
    }
    else if (intBitsToFloat(brickValue) > -MIN_SAFE_DF)
    {
        // entrance is treated as a temporary storage here; it will be reassigned anyway before being used for its intended purpose
        entrance = mix(rayPosition - brickPosition, brickPosition + 1 - rayPosition, step(vec3(0), dir)) * timeToCross;
        lastAxis = indexOfMinVec3(entrance);
        depth = entrance[lastAxis]; // Brick-space depth; it should be converted to voxel space by multiplying by 4 before returning
    }

    // Traversing bricks along the ray direction

    while(true)
    {
        if (brickValue >= 0 || intBitsToFloat(brickValue) > -MIN_SAFE_DF) // If the last traversed brick were occupied (DF value is unknown) or the DF value is too small, perform DDA step to the next brick
        {
            // lastAxis and depth (brick space) should be calculated on previous iteration
            brickPosition[lastAxis] += gridStep[lastAxis];
            rayPosition = dir * depth + origin / 4;
            rayPosition[lastAxis] = round(rayPosition[lastAxis]); // Snap just in case
        }
        else // If the last traversed brick were empty and distance field value is large enough, perform jump
        {
            vec3 pointInNearestSafeBrick = dir * -intBitsToFloat(brickValue) + rayPosition;

            vec3 nearestSafeSides = mix(ceil(pointInNearestSafeBrick), floor(pointInNearestSafeBrick), step(vec3(0.0), dir));
            vec3 timeToNearestSafeSides = (nearestSafeSides - rayPosition) * dir_safe_div; // timeToCross is a reciprocal of abs of dir but we need signed dir here
        
            lastAxis = indexOfMaxVec3(timeToNearestSafeSides);
            float maxSafeTime = timeToNearestSafeSides[lastAxis];
            depth += maxSafeTime;
            
            rayPosition += dir * maxSafeTime;
            rayPosition[lastAxis] = nearestSafeSides[lastAxis]; // Snap just in case
            brickPosition = any(lessThan(pointInNearestSafeBrick, vec3(0))) ? ivec3(-1) : ivec3(pointInNearestSafeBrick);
        }

        if (any(lessThan(brickPosition, ivec3(0))) || any(greaterThanEqual(brickPosition, voxelBrickmapSize)))
        {
            hitPosition = (depth * 4) * dir + origin; // Depth should be converted to voxel space by multiplying by 4 before returning
            normal = 0;
            return 1;
        }
        else 
        {
            brickValue = getBrickValueDirect(brickPosition);

                // Traversing voxels of a brick
            if (brickValue >= 0)
            {
                uint bitmask0 = brickOccupancyList[(brickValue << 1)];
                uint bitmask1 = brickOccupancyList[(brickValue << 1) + 1];

                entrance = fract(rayPosition) * 4;

//                // highlight edges of bricks
//                float debugGridThickness = 0.1;
//                ivec3 isEdge = ivec3(lessThan(entrance, vec3(debugGridThickness))) + ivec3(greaterThan(entrance, vec3(4 - debugGridThickness)));
//                if (isEdge.x + isEdge.y + isEdge.z > 1)
//                {
//                    return 2;
//                }

                entrance[lastAxis] = dir[lastAxis] > 0 ? 0 : 4;
                ivec3 entranceVoxel = ivec3(entrance);
                entranceVoxel[lastAxis] = dir[lastAxis] > 0 ? 0 : 3;

                bool hit = traverseBrick(bitmask0, bitmask1, entrance, entranceVoxel, dir, timeToCross, hitVoxel, lastAxis, intersectionTime);

                depth += intersectionTime * 0.25;

                if (hit)
                {
                    normal = normalIndexFromDir(dir, lastAxis);
                    brickOffset = brickPosition << 2;
                    hitPosition = dir * intersectionTime + entrance + brickOffset;
                    depth *= 4; // Depth should be converted to voxel space by multiplying by 4 before returning
                    voxelHitPosition = hitVoxel + brickOffset;
                    return 0;
                }
            }
            else if (intBitsToFloat(brickValue) > -MIN_SAFE_DF) 
            {
                // entrance is treated as a temporary storage
                entrance = mix(rayPosition - brickPosition, brickPosition + 1 - rayPosition, step(vec3(0), dir)) * timeToCross;
                lastAxis = indexOfMinVec3(entrance);
                depth += entrance[lastAxis];
            }
        }
    }
}

bool traverseBrick(uint bitmask0, uint bitmask1, vec3 startingPosition, ivec3 voxelPosition, vec3 dir, vec3 timeToCross, out ivec3 hitVoxel, inout int lastAxis, out float intersectionTime)
{
    vec3 nextIntersectionTime = mix(startingPosition - voxelPosition, voxelPosition + 1.0 - startingPosition, step(vec3(0.0), dir));
    nextIntersectionTime *= timeToCross;

    uint voxelIndex = (voxelPosition.y << 4) + (voxelPosition.z << 2) + voxelPosition.x;

    if (getVoxelBit(bitmask0, bitmask1, voxelIndex) > 0)
    {
        hitVoxel = voxelPosition;
        intersectionTime = 0;
        return true;
    }

    while (true)
    {
        lastAxis = indexOfMinVec3(nextIntersectionTime);

        int way = int(sign(dir[lastAxis]));

        if (voxelPosition[lastAxis] == (way < 0 ? 0 : 3))
        {
            intersectionTime = nextIntersectionTime[lastAxis];
            hitVoxel = voxelPosition;
            return false;
        }
                
        voxelIndex += (1 << ((lastAxis == 2 ? 1 : (lastAxis == 1 ? 2 : 0)) << 1)) * way;
        voxelPosition[lastAxis] += way;


        if (getVoxelBit(bitmask0, bitmask1, voxelIndex) > 0)
        {
            intersectionTime = nextIntersectionTime[lastAxis];
            hitVoxel = voxelPosition;
            return true;
        }

        nextIntersectionTime[lastAxis] += timeToCross[lastAxis];
    }
}

uint getVoxelValue(ivec3 voxelPosition) 
{
    int brickValue = getBrickValueDirect(voxelPosition >> 2);
    if (brickValue == -1) return 0;
    ivec3 voxelLocalPosition = (voxelPosition & 3);
    uint voxelPack = brickValueList[brickValue * brickSizeInUINTS + ((voxelLocalPosition.y << 2) + voxelLocalPosition.z)];
    int shift = voxelLocalPosition.x << 3;
    return (voxelPack >> shift) & 255;
}

int getBrickValueDirect(ivec3 brickPosition) 
{
    return brickIndices[brickPosition.y * voxelBrickmapSize.x * voxelBrickmapSize.z + 
                        brickPosition.z * voxelBrickmapSize.x +
                        brickPosition.x];
}

uint getVoxelBit(uint bitmask0, uint bitmask1, uint voxelIndex)
{
    uint b0 = bitmask0 & (1 << voxelIndex);
    uint b1 = bitmask1 & (1 << (voxelIndex - 32));
    return voxelIndex < 32 ? b0 : b1;
}

vec3 skySample(vec3 dir)
{
    float sunVisibility = acos(clamp(-dot(dir, sunDirection), -1, 1)) * INV_PI;
    sunVisibility = clamp(64 * (sunVisibility - 0.98), 0, 1);

    return mix(vec3(0.75, 1.3, 1.9) * 2.7, sunColor, sunVisibility);
}

vec3 sunSample(vec3 pos, vec3 dir)
{
    vec3 fl_hpos; ivec3 fl_vhpos; float fl_d; int fl_n;
    return sunColor * raycast(pos, dir, fl_hpos, fl_vhpos, fl_d, fl_n);
}

vec3 getDiffuseReflectionDir(int normal, int sampleIndex)
{
    float key1 = rand01From_vec2(uv * sampleIndex); 
    float key2 = rand01From_vec2((key1 + uv) * 0.5);
    return rotateVerticalByNormal(randomVector(vec2(key1, key2), sampleIndex), normal);
}

int normalIndexFromDir(vec3 dir, int axis)
{
    return dir[axis] > 0 ? (axis << 1) : (axis << 1) + 1;
}

vec3 rotateVerticalByNormal(vec3 vector, int normal)
{
    switch (normal)
    {
        case 0: return vec3(-vector.y, vector.x, vector.z);
        case 1: return vec3(vector.y, -vector.x, vector.z);
        case 2: return -vector;
        case 3: return vector;
        case 4: return vec3(vector.x, vector.z, -vector.y);
        case 5: return vec3(vector.x, -vector.z, vector.y);
    }
    return vector;
}

vec3 vecNormal(int normal)
{
    vec3 vect = vec3(0);
    vect[normal >> 1] = ((normal & 1) << 1) - 1;
    return vect;
}

vec3 randomVector(vec2 key, int sampleIndex)
{
    float phi = jitterArc * sampleIndex + jitterArc * key.x + arcDisplacement;
    float cosTheta = sqrt(1.0f - key.y);
    float sinTheta = sqrt(key.y);
    return vec3(cos(phi) * cosTheta, sinTheta, sin(phi) * cosTheta);
}

float rand01From_vec2(vec2 point) 
{
    point *= randSaltLocal;
    return fract(sin(dot(point.xy, vec2(12.9898,75.233))) * 43758.5453123);
}

uint wang_hash(uint seed)
{
    seed = (seed ^ 61u) ^ (seed >> 16);
    seed *= 9u;
    seed = seed ^ (seed >> 4);
    seed *= 668265261u;
    seed = seed ^ (seed >> 15);
    return seed;
}

uint wangHashFrom_uvec3(uvec3 point)
{
    uint h = wang_hash(point.x);
    h = wang_hash(h + point.y);
    return wang_hash(h + point.z);
}

float minVec3(vec3 vect)
{
    return min(min(vect.x, vect.y), vect.z);
}

float maxVec3(vec3 vect)
{
    return max(max(vect.x, vect.y), vect.z);
}

int indexOfMinVec3(vec3 vect)
{
    return vect.x < vect.y ? (vect.x < vect.z ? 0 : 2) : (vect.y < vect.z ? 1 : 2);
}

int indexOfMaxVec3(vec3 vect)
{
    return vect.x > vect.y ? (vect.x > vect.z ? 0 : 2) : (vect.y > vect.z ? 1 : 2);
}

vec3 sph2Cart(float phi, float theta)
{
    float cosTheta = cos(theta);
    return vec3(cos(phi) * cosTheta, sin(theta), sin(phi) * cosTheta);
}

vec3 rodriguesRotation(vec3 v, vec3 axis, float theta)
{
    float cosTheta = cos(theta);
    return v * cosTheta + cross(axis, v) * sin(theta) + axis * dot(axis, v) * (1 - cosTheta);
}
vec3 simpleRodriguesRotation(vec3 v, vec3 normal, float theta)
{
    return cos(theta) * v + sin(theta) * cross(v, normal);
}

vec3 jitterVector(vec3 v, float theta, float amount)
{
    return rodriguesRotation(simpleRodriguesRotation(v, cross(v, vec3(1, 0, 0)), amount), v, theta);
}
