#version 430 core

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;


// Texture samplers

layout(location = 7) uniform sampler2D skyTex;


// Image variables

layout(rgba32f, binding = 0) uniform image2D luminance_depthImg;

layout(rgba32f, binding = 1) uniform image2D normalCompound_motionImg;

// Input

struct material
{
    vec3 color;
    // 4 bytes padding
    vec3 emission;
    // 4 bytes padding
};

struct voxelBrick
{
    uint bitmask[2];
    uint packs[16];
};

layout(std430, binding = 0) buffer brickListSSBO
{
    uint brickList[];
};

layout(std430, binding = 1) buffer brickIndicesSSBO
{
    int brickIndices[];
};

layout(std430, binding = 2) buffer palette
{
    material materialPalette[];
};

layout(std140, binding = 3) buffer inputData
{
    mat4 cameraMatrix;
    mat4 invCameraMatrix;
    mat4 prevCameraMatrix;
    vec3 cameraPosition;
    float randSalt;
    vec3 prevCameraPosition;
};

layout(location = 0) uniform ivec3 mapSize;
layout(location = 1) uniform ivec3 voxelBrickmapSize;
layout(location = 2) uniform vec3 sunDirection = vec3(0.904, 0.361, 0.226);//vec3(0.31, 0.82, 0.47);
layout(location = 3) uniform vec3 sunColor = vec3(6.8, 4.65, 2);
layout(location = 4) uniform float sunDirectionJitter = 0.01;

layout(location = 5) uniform int cycle = 0;
layout(location = 6) uniform int samples = 1;
float invSamples = 1.0 / samples;


// Global vars

const float PI = 3.141592;
const float TWO_PI = 6.283185;
const float INV_PI = 1 / PI;
const float INV_TWO_PI = 1 / TWO_PI;
const int intMaxValue = 2147483647;


vec2 uv;
vec2 fragPosition;
float jitterArc = TWO_PI / samples;
float arcDisplacement;

float randSaltLocal;

const float depthBias = -0.001;
const int brickSizeInUINTS = 18;


// Function prototypes

void executePathTracing(vec3 origin, vec3 dir, out vec3 luminance, out float depth, out int normal, out vec3 hitPosition);

int raycast(vec3 origin, vec3 dir, out vec3 hitPosition, out ivec3 voxelHitPosition, out float depth, out int normal);
bool traverseBrick(uint bitmask0, uint bitmask1, vec3 startingPosition, ivec3 voxelPosition, vec3 dir, vec3 timeToCross, uint brickIndex, out ivec3 hitVoxel, out int lastAxis);

float minVec3(vec3 vect);
float maxVec3(vec3 vect);
vec3 sph2Cart(float phi, float theta);

vec3 rodriguesRotation(vec3 v, vec3 axis, float theta);
vec3 simpleRodriguesRotation(vec3 v, vec3 normal, float theta);
vec3 rotateVerticalByNormal(vec3 vector, int normal);
int normalIndexFromDir(vec3 dir, int axis);

vec3 skySample(vec3 dir);
vec3 sunSample(vec3 pos, vec3 dir);

vec3 getDiffuseReflectionDir(int normal, int sampleIndex);
vec3 randomVector(vec2 key, int sampleIndex);
float random (vec2 point);
vec3 jitterVector(vec3 v, float theta, float amount);
vec3 vecNormal(int normal);

uint getBrickIndex(ivec3 voxelPosition); 
uint getBrickIndexDirect(ivec3 brickPosition);
uint getVoxelValue(ivec3 voxelPosition);
uint getVoxelBit(uint bitmask0, uint bitmask1, uint voxelIndex);

void main() 
{
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 resolution = imageSize(luminance_depthImg);
    uv = (vec2(texelCoord) + 0.5) / resolution;
    fragPosition = uv * 2 - 1;

    randSaltLocal = randSalt;
    arcDisplacement = random(uv * (randSalt - 1));
    invSamples = 1.0 / samples;

    vec4 viewPoint = vec4(fragPosition, 1, 1);
    vec4 transformedViewPoint = invCameraMatrix * viewPoint;
    vec3 rayDirection = normalize(transformedViewPoint.xyz / transformedViewPoint.w);

    vec3 lum; float depth = 0; int normal; vec3 hitPos;
    executePathTracing(cameraPosition, rayDirection, lum, depth, normal, hitPos);

    vec2 prevUV;
    vec2 motion;
    vec3 prevCameraToHitPos = hitPos - prevCameraPosition;

    vec4 normalCompound_Motion = imageLoad(normalCompound_motionImg, texelCoord);

    // Find reprojection coord
    vec3 prevRayDirection = normalize(prevCameraToHitPos);
    vec4 prevViewPoint = prevCameraMatrix * vec4(prevRayDirection, 0);
    prevUV = fma(prevViewPoint.xy / prevViewPoint.w, vec2(0.5), vec2(0.5));
    ivec2 reprojectionCoord = ivec2(prevUV * resolution);

    vec4 prevNormalCompound_motion = imageLoad(normalCompound_motionImg, reprojectionCoord);
    float prevDepth = prevNormalCompound_motion.y;

    int prevReprojectedNormal = (int(prevNormalCompound_motion.x) >> 3 * cycle) & 7;
    int prevNormalAtCurrentPixel = (int(normalCompound_Motion.x) >> 3 * cycle) & 7;

    if (normal == prevReprojectedNormal)
    {
        vec3 prevHit = prevRayDirection * prevDepth + prevCameraPosition;
        if (abs(prevHit[normal >> 1] - hitPos[normal >> 1]) < 0.2)
        {
            if (abs(distance(prevHit, hitPos)) < pow(dot(vecNormal(normal), rayDirection) + 1.3, 5) * 10)
            {
                motion = prevUV - uv;
            }
        }
        else
        {
            motion = reprojectionCoord;
        }
    }
    else 
    {
        motion = vec2(3);
    }

//    if (abs(length(prevCameraToHitPos) - prevDepth) < pow(dot(vecNormal(normal), rayDirection) + 1.3, 5) * 10)
//    {
//        motion = prevReprojectedNormal == normal ? prevUV - uv : vec2(3);
//    }
//    else
//    {
//        motion = reprojectionCoord;
//    }

    int normalCompound = (prevNormalAtCurrentPixel << (cycle * 3)) | (normal << (cycle * -3 + 3)) | (normal << 6) | (prevNormalAtCurrentPixel << 9);
    imageStore(normalCompound_motionImg, texelCoord, vec4(normalCompound, normalCompound_Motion.y, motion));
    imageStore(luminance_depthImg, texelCoord, vec4(lum, depth));
}


void executePathTracing(vec3 origin, vec3 dir, out vec3 luminance, out float depth, out int normal, out vec3 hitPosition)
{
    ivec3 firstHitVoxel;
    material firstHitMat;
    material secondHitMat;
    vec3 firstHitNormal;

    int firstHitResult = raycast(origin, dir, hitPosition, firstHitVoxel, depth, normal);
    hitPosition += dir * depthBias;
    firstHitMat = materialPalette[getVoxelValue(firstHitVoxel)];
    firstHitNormal = vecNormal(normal);
    int secondHitResult;

    if (firstHitResult == 1)
    {
        luminance = skySample(dir);
        return;
    }

    vec3 directLighting = firstHitMat.emission;
    vec3 indirectContribution = vec3(0);

    int i = 1;
    while(i <= samples)
    {
        vec3 secondHitPos;
        ivec3 secondHitVoxel;
        int secondHitNormalInt;
        float secondHitDepth;

        vec3 scatteredDir;
        scatteredDir = getDiffuseReflectionDir(normal, i);
        
        secondHitResult = raycast(hitPosition, scatteredDir, secondHitPos, secondHitVoxel, secondHitDepth, secondHitNormalInt);
        secondHitMat = materialPalette[getVoxelValue(secondHitVoxel)];

        if (secondHitResult == 0)
        {
            float incomingCosineWeight = clamp(dot(firstHitNormal, scatteredDir), 0, 1);
            indirectContribution += secondHitMat.emission * incomingCosineWeight;

            float key1 = random(fragPosition.xy * invSamples * i) * TWO_PI;
            float key2 = random(vec2(key1 * 1.23, key1 * 0.914)) * sunDirectionJitter;
            indirectContribution += sunSample(secondHitPos, jitterVector(sunDirection, key1, key2)) * secondHitMat.color * clamp(dot(vecNormal(secondHitNormalInt), sunDirection), 0, 1) * incomingCosineWeight;
            i++;
            continue;
        }
        if (secondHitResult == 1)
        {
            indirectContribution += skySample(scatteredDir) * clamp(dot(firstHitNormal, scatteredDir), 0, 1);
            i++;
            continue;
        }
        i++;
    }

    float key1 = random(fragPosition.xy * 92.92) * TWO_PI;
    float key2 = random(vec2(key1 * 32.2, key1 * 51.1)) * sunDirectionJitter;
    directLighting += sunSample(hitPosition, jitterVector(sunDirection, key1, key2)) * clamp(dot(firstHitNormal, sunDirection), 0, 1);

    luminance = (directLighting + indirectContribution * invSamples) * firstHitMat.color;
}

int raycast(vec3 origin, vec3 dir, out vec3 hitPosition, out ivec3 voxelHitPosition, out float depth, out int normal)
{
    ivec3 originVoxel = ivec3(origin);
    ivec3 brickPosition = originVoxel >> 2;
    vec3 brickSpaceOrigin = origin / 4;
    uint brickIndex = getBrickIndexDirect(brickPosition);
    ivec3 brickOffset = originVoxel & (~3);
    vec3 entrance;
    vec3 timeToCross = 1 / abs(dir);
    ivec3 hitVoxel;
    int lastAxis;
    int lastWideAxis;
    float lastWideDepth = 0;

    ivec3 gridStep = ivec3(dir.x > 0 ? 1 : -1, dir.y > 0 ? 1 : -1, dir.z > 0 ? 1 : -1);
    vec3 nextBrickIntersectionTime = vec3(
            dir.x < 0 ? brickSpaceOrigin.x - brickPosition.x : brickPosition.x + 1 - brickSpaceOrigin.x,
            dir.y < 0 ? brickSpaceOrigin.y - brickPosition.y : brickPosition.y + 1 - brickSpaceOrigin.y,
            dir.z < 0 ? brickSpaceOrigin.z - brickPosition.z : brickPosition.z + 1 - brickSpaceOrigin.z);
    nextBrickIntersectionTime *= timeToCross;

    if (brickIndex != 0)
    {
        uint bitmask0 = brickList[brickIndex * brickSizeInUINTS];
        uint bitmask1 = brickList[brickIndex * brickSizeInUINTS + 1];
        entrance = origin - brickOffset;

        bool hit = traverseBrick(bitmask0, bitmask1, entrance, originVoxel & 3, dir, timeToCross, brickIndex, hitVoxel, lastAxis);
        if (hit)
        {
            if (lastAxis == -1)
            {
                hitPosition = origin;
                voxelHitPosition = originVoxel;
                normal = -1;
                depth = 0;
                return 0;
            }
            
            float localDistance = abs((dir[lastAxis] > 0 ? hitVoxel[lastAxis] : hitVoxel[lastAxis] + 1) - entrance[lastAxis]) * timeToCross[lastAxis];

            depth = localDistance;
            hitPosition = dir * localDistance + origin;
            voxelHitPosition = hitVoxel + brickOffset;
            normal = normalIndexFromDir(dir, lastAxis);
            return 0;
        }
    }

    // Traversing bricks along the ray direction
    while (true)
    {
        lastWideAxis = nextBrickIntersectionTime.x <= nextBrickIntersectionTime.y
                ? nextBrickIntersectionTime.x <= nextBrickIntersectionTime.z ? 0 : 2
                : nextBrickIntersectionTime.y <= nextBrickIntersectionTime.z ? 1 : 2;

        if (lastWideAxis == 0)
        {
            brickPosition.x += gridStep.x;
            lastWideDepth = nextBrickIntersectionTime.x;
            nextBrickIntersectionTime.x += timeToCross.x;
        }
        else if(lastWideAxis == 1)
        {
            brickPosition.y += gridStep.y;
            lastWideDepth = nextBrickIntersectionTime.y;
            nextBrickIntersectionTime.y += timeToCross.y;
        }
        else
        {
            brickPosition.z += gridStep.z;
            lastWideDepth = nextBrickIntersectionTime.z;
            nextBrickIntersectionTime.z += timeToCross.z;
        }

        brickOffset = brickPosition << 2;

        if (!(all(greaterThanEqual(brickPosition, ivec3(0))) && all(lessThan(brickPosition, voxelBrickmapSize))))
        {
            depth = lastWideDepth;
            hitPosition = dir * depth + origin;
            normal = -1;
            return 1;
        }

        brickIndex = getBrickIndexDirect(brickPosition);

        // Traversing voxels of a brick
        if (brickIndex != -1)
        {
            uint bitmask0 = brickList[brickIndex * brickSizeInUINTS];
            uint bitmask1 = brickList[brickIndex * brickSizeInUINTS + 1];
            entrance = lastWideDepth * dir + brickSpaceOrigin;

            entrance -= ivec3(entrance);
            entrance[lastWideAxis] = dir[lastWideAxis] > 0 ? 0 : 1;
            entrance *= 4;
            ivec3 entranceVoxel = ivec3(entrance);
            entranceVoxel[lastWideAxis] = dir[lastWideAxis] > 0 ? 0 : 3;

            bool hit = traverseBrick(bitmask0, bitmask1, entrance, entranceVoxel, dir, timeToCross, brickIndex, hitVoxel, lastAxis);

            if (hit)
            {
                lastAxis = lastAxis == -1 ? lastWideAxis : lastAxis;
                normal = normalIndexFromDir(dir, lastAxis);

                float localDistance = abs((dir[lastAxis] > 0 ? hitVoxel[lastAxis] : hitVoxel[lastAxis] + 1) - entrance[lastAxis]) * timeToCross[lastAxis];
                hitPosition = dir * localDistance + entrance + brickOffset;
                depth = length(hitPosition - origin);
                voxelHitPosition = hitVoxel + brickOffset;
                return 0;
            }
        }
    }
}

bool traverseBrick(uint bitmask0, uint bitmask1, vec3 startingPosition, ivec3 voxelPosition, vec3 dir, vec3 timeToCross, uint brickIndex, out ivec3 hitVoxel, out int lastAxis)
{
    vec3 nextIntersectionTime = vec3(
        dir.x < 0 ? startingPosition.x - voxelPosition.x : voxelPosition.x + 1 - startingPosition.x,
        dir.y < 0 ? startingPosition.y - voxelPosition.y : voxelPosition.y + 1 - startingPosition.y,
        dir.z < 0 ? startingPosition.z - voxelPosition.z : voxelPosition.z + 1 - startingPosition.z);
    nextIntersectionTime *= timeToCross;

    uint voxelIndex = (voxelPosition.y << 4) + (voxelPosition.z << 2) + voxelPosition.x;

    if (getVoxelBit(bitmask0, bitmask1, voxelIndex) > 0)
    {
        hitVoxel = voxelPosition;
        lastAxis = -1;
        return true;
    }

    int axisToStep;

    while (true)
    {
        axisToStep = nextIntersectionTime.x <= nextIntersectionTime.y ?
        (nextIntersectionTime.x <= nextIntersectionTime.z ? 0 : 2) :
        (nextIntersectionTime.y <= nextIntersectionTime.z ? 1 : 2);

        int way = int(sign(dir[axisToStep]));

        if (voxelPosition[axisToStep] == (way < 0 ? 0 : 3))
            break;
                
        voxelIndex += (1 << ((axisToStep == 2 ? 1 : (axisToStep == 1 ? 2 : 0)) << 1)) * way;
        voxelPosition[axisToStep] += way;

        nextIntersectionTime[axisToStep] += timeToCross[axisToStep];

        if (getVoxelBit(bitmask0, bitmask1, voxelIndex) > 0)
        {
            hitVoxel = voxelPosition;
            lastAxis = axisToStep;
            return true;
        }
    }

    hitVoxel = voxelPosition;
    lastAxis = axisToStep;
    return false;
}

uint getVoxelValue(ivec3 voxelPosition) 
{
    uint brickIndex = getBrickIndex(voxelPosition);
    if (brickIndex == -1) return 0;
    ivec3 voxelLocalPosition = (voxelPosition & 3);
    uint voxelPack = brickList[brickIndex * brickSizeInUINTS + 2 + ((voxelLocalPosition.y << 2) + voxelLocalPosition.z)];
    int shift = voxelLocalPosition.x << 3;
    return (voxelPack >> shift) & 255;
}

uint getBrickIndex(ivec3 voxelPosition) 
{
    ivec3 brickPosition = ivec3(voxelPosition.x >> 2, voxelPosition.y >> 2, voxelPosition.z >> 2);
    return brickIndices[brickPosition.y * voxelBrickmapSize.x * voxelBrickmapSize.z + 
                        brickPosition.z * voxelBrickmapSize.x +
                        brickPosition.x];
}

uint getBrickIndexDirect(ivec3 brickPosition) 
{
    return brickIndices[brickPosition.y * voxelBrickmapSize.x * voxelBrickmapSize.z + 
                        brickPosition.z * voxelBrickmapSize.x +
                        brickPosition.x];
}

uint getVoxelBit(uint bitmask0, uint bitmask1, uint voxelIndex)
{
    if (voxelIndex < 32)
    {
        return bitmask0 & (1 << voxelIndex);
    }
    else 
    {
        return bitmask1 & (1 << (voxelIndex - 32));
    }
}

vec3 skySample(vec3 dir)
{
//    float theta = atan(dir.z, dir.x);
//    float phi = asin(dir.y);
//
//    vec2 uv = vec2(theta * INV_TWO_PI + 0.5, phi * INV_PI + 0.5);
//
//    return texture(skyTex, uv).rgb;
    
//    return vec3(0.75, 1.3, 1.9);

    float absFactor = fma(tanh(5 * dir.y - 0.5), 0.5, 0.5);
    return mix(vec3(3.7, 1.2, 0.4), vec3(0.188, 0.192, 0.459), absFactor);
}

vec3 sunSample(vec3 pos, vec3 dir)
{
    vec3 fl_hpos; ivec3 fl_vhpos; float fl_d; int fl_n;
    return sunColor * raycast(pos, dir, fl_hpos, fl_vhpos, fl_d, fl_n);
}

vec3 getDiffuseReflectionDir(int normal, int sampleIndex)
{
    float key1 = random(uv * sampleIndex); 
    float key2 = random((key1 + uv) * 0.5);
    return rotateVerticalByNormal(randomVector(vec2(key1, key2), sampleIndex), normal);
}

int normalIndexFromDir(vec3 dir, int axis)
{
    return dir[axis] > 0 ? (axis << 1) : (axis << 1) + 1;
}

vec3 rotateVerticalByNormal(vec3 vector, int normal)
{
    switch (normal)
    {
        case 0: return vec3(-vector.y, vector.x, vector.z);
        case 1: return vec3(vector.y, -vector.x, vector.z);
        case 2: return -vector;
        case 3: return vector;
        case 4: return vec3(vector.x, vector.z, -vector.y);
        case 5: return vec3(vector.x, -vector.z, vector.y);
    }
    return vector;
}

vec3 vecNormal(int normal)
{
    vec3 vect = vec3(0);
    vect[normal >> 1] = ((normal & 1) << 1) - 1;
    return vect;
}

vec3 randomVector(vec2 key, int sampleIndex)
{
    float phi = jitterArc * sampleIndex + jitterArc * key.x + arcDisplacement;
    float cosTheta = sqrt(1.0f - key.y);
    float sinTheta = sqrt(key.y);
    return vec3(cos(phi) * cosTheta, sinTheta, sin(phi) * cosTheta);
}

float random (vec2 point) 
{
    point *= randSaltLocal;
    return fract(sin(dot(point.xy, vec2(12.9898,75.233))) * 43758.5453123);
}

float minVec3(vec3 vect)
{
    return min(min(vect.x, vect.y), vect.z);
}

float maxVec3(vec3 vect)
{
    return max(max(vect.x, vect.y), vect.z);
}

vec3 sph2Cart(float phi, float theta)
{
    float cosTheta = cos(theta);
    return vec3(cos(phi) * cosTheta, sin(theta), sin(phi) * cosTheta);
}

vec3 rodriguesRotation(vec3 v, vec3 axis, float theta)
{
    float cosTheta = cos(theta);
    return v * cosTheta + cross(axis, v) * sin(theta) + axis * dot(axis, v) * (1 - cosTheta);
}
vec3 simpleRodriguesRotation(vec3 v, vec3 normal, float theta)
{
    return cos(theta) * v + sin(theta) * cross(v, normal);
}

vec3 jitterVector(vec3 v, float theta, float amount)
{
    return rodriguesRotation(simpleRodriguesRotation(v, cross(v, vec3(1, 0, 0)), amount), v, theta);
}
