#version 430 core

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

// Output texture
layout(rgba32f, binding = 0) uniform image2D tex;

layout(std430, binding = 0) buffer brickListSSBO
{
    int brickList[];
};

layout(std430, binding = 1) buffer bricksSSBO
{
    int brickmap[];
};

void main() 
{
	ivec2 texelCoord = ivec2(gl_WorkGroupID.xy);
    vec2 fragPosition = vec2(texelCoord) / imageSize(tex);
    
    vec3 col = vec3(fragPosition, 0);

    if (brickList[brickmap[9]] == 4)
    {
        col = vec3(1, 1, 0);
    }

	imageStore(tex, texelCoord, vec4(col, 1));
}